### ISSUE TITLE
Slack channel output support

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/terraform-provider-opsgenie#102]
Most of our team would like to receive their alerts to team channel. 
That is a good start on long way to good alerting with app and phone calls.
Please add support for opsgenie_api_integration for slack usage.

**Comment by ffahri** [comment]
Hey @freeseacher 
Slack integration needs to be confirmed from Slack workspace. Therefore in Opsgenie UI, this will forward you to slack and it expects a user to select workspace and correct channel to install the Opsgenie Slack app.
If you try to create SlackApp from API you will get this error

```
Error: Error occurred with Status code: 403, Message: SlackApp integrations cannot be created from API
```

https://docs.opsgenie.com/docs/slack-app-integration

**Comment by freeseacher** [comment]
yep i know. but that is a huge pain for me.

**Comment by ffahri** [comment]
I will pass this request to internal teams, but like I said it needs confirmation from the Slack side.

**Comment by nikolay** [comment]
@ffahri We have GitHub, Terraform Cloud, pretty much everything as code... except our Slack integration in Opsgenie. Please, escalate this feature request!

**Comment by ffahri** [comment]
@nikolay This integration needs an user input and cannot be done using api

**Comment by ghost** [comment]
@ffahri You can definitely make this configurable so it doesn't need to go through the UI. I was using Pagerduty previously and could dynamically configure a Slack integration from Terraform, parameterizing the channel, etc. I think you all should definitely do this, I'm 100% with @nikolay that this is an essential feature. You can not expect organizations using Terraform to manually set this up in the UI. Maybe you all will need to crack open the Opsgenie internals and how you architect your API integrations and add this to the Opsgenie API to make it so this will work from the Terraform provider. I think that you all have to cross that bridge if you want to claim a fully-featured Terraform provider that's actually valuable to any organization using Slack. I am just now evaluating Opsgenie and this is already a showstopper for us.

**Comment by ghost** [comment]
it at least seems possible to create an app via a manifest via api access?

https://api.slack.com/methods/apps.manifest.create

I'm not a slack app dev, so I really don't know if this is sufficient (e.g. in some workspaces apps need to be approved by an admin, before they can get used).

ymmv, HTH

**Comment by KarstenSiemer** [comment]
support for this would be much appreciated
