### ISSUE TITLE
Heartbeat not found error when heartbeat is manually removed via UI

### ISSUE THREAD

**Issue by TheoBrigitte** [opsgenie/terraform-provider-opsgenie#103]
### Terraform Version
```
$ terraform -v
Terraform v0.12.24
+ provider.opsgenie v0.3.1
```

### Affected Resource(s)
- opsgenie_heartbeat

### Terraform Configuration Files
```hcl
resource "opsgenie_heartbeat" "heartbeat" {
  for_each = toset(var.list)

  alert_message  = "Heartbeat [${each.value}] is expired."
  alert_priority = "P3"
  enabled        = true
  interval       = 25
  interval_unit  = "minutes"
  name           = each.value
}

variable "list" {
  description = "list of heartbeats name"
  type        = list(string)
  default = [
    "foo",
    "bar",
  ]
}
provider "opsgenie" {
  api_key = var.opsgenie_api_key
  api_url = "api.opsgenie.com"
  version = "~> 0.3"
}
variable "opsgenie_api_key" {
  description = "Opsgenie API key used for authentication"
}
```

### Debug Output
https://gist.github.com/TheoBrigitte/3229acc560a03278c8c5181c5b9598e2

### Expected Behavior
* refresh command to succeed and remove the missing heartbeat from the state
* know which heartbeat triggered this error

### Actual Behavior
* refresh command failed and state was not updated
* error is missing the heartbeat id

### Steps to Reproduce

1. `terraform apply`
2. Manually remove 1 heartbeat via opsgenie UI
3. `terraform refresh`

### References
Might be related to https://github.com/terraform-providers/terraform-provider-opsgenie/issues/101

**Comment by ffahri** [comment]
Hey @TheoBrigitte this will be implemented all resources with this issue https://github.com/terraform-providers/terraform-provider-opsgenie/issues/101

**Comment by TheoBrigitte** [comment]
Ok fine, I was not 100% sure so I thought I'd raise awareness on this.

**Comment by ffahri** [comment]
Thank you for pr also @TheoBrigitte
