### ISSUE TITLE
opsgenie_api_integrations: API Key is not granted with write access.

### ISSUE THREAD

**Issue by AlexeyShchukinSecurrency** [opsgenie/terraform-provider-opsgenie#107]
Hi there,

I ran into an issue when `allow_write_access` attribute for resources created by terraform *equals false* if it wasn't specified explicitly in resource definition. It leads to the following error on the alertmanager side:
```
level=error ts=2020-05-19T22:05:14.942Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 403: {\"code\":40301,\"message\":\"API Key is not granted with write access.\",\"took\":0.002,\"requestId\":\"30d11c73-89ce-4e3c-a6b5-b586d40f20b0\"}" context_err=null
```
In order to eliminate this issue, `allow_write_access` must be set to `true` explicitly.

[According to official documentation](https://www.terraform.io/docs/providers/opsgenie/r/api_integration.html#allow_write_access), `allow_write_access` must have `true` value by default. But, [it looks like it doesn't](https://github.com/terraform-providers/terraform-provider-opsgenie/blob/f8e4a5e5747c124c35658bc201fbeb41419605d6/opsgenie/resource_opsgenie_api_integration.go#L34).

Moreover, in spite of how object was created (by terraform or manually and then imported) and whether `opsgenie_api_integration` has explicitly defined `allow_write_access = true` or not, from terraform point of view `allow_write_access` always equals `false`.
In case `opsgenie_api_integration` resource *has* `allow_write_access = true`, then terraform tries to update already consistent resource. Always.

One more thing, it seems official documentation page for `opsgenie_api_integration` contains a typo in [Import section](https://www.terraform.io/docs/providers/opsgenie/r/api_integration.html#import):
```
$ terraform import opsgenie_team.team1 812be1a1-32c8-4666-a7fb-03ecc385106c

instead

$ terraform import opsgenie_api_integration.foo 812be1a1-32c8-4666-a7fb-03ecc385106c
```

### Terraform Version
```
$ terraform version
Terraform v0.12.24
+ provider.opsgenie v0.3.1
```

### Affected Resource(s)
- opsgenie_api_integrations

### Debug Output
```
# terraform console

# this resource was imported (and has no api_key field, btw)
> opsgenie_api_integration.prometheus_imported
{
  "allow_write_access" = false
  "enabled" = true
  "id" = "<<uuid>>"
  "name" = "Prometheus_Imported"
  "responders" = []
  "suppress_notifications" = false
  "type" = "Prometheus"
}

# this resource was created by terraform
> opsgenie_api_integration.prometheus_global
{
  "allow_write_access" = false
  "api_key" = "<<redacted>>"
  "enabled" = true
  "id" = "<<uuid>>"
  "name" = "Prometheus_Global"
  "responders" = []
  "suppress_notifications" = false
  "type" = "Prometheus"
}

# this resource was created by terraform
> opsgenie_api_integration.prometheus_team
{
  "allow_write_access" = false
  "api_key" = "<<redacted>>"
  "enabled" = true
  "id" = "<<uuid>>"
  "name" = "Prometheus_Team"
  "owner_team_id" = "<<uuid>>"
  "responders" = []
  "suppress_notifications" = false
  "type" = "Prometheus"
}
```

### Panic Output
No.

### Terraform Configuration Files
```hcl
resource "opsgenie_api_integration" "prometheus_foo" {
  name               = "Prometheus_Foo"
  type               = "Prometheus"
  allow_write_access = true
}
resource "opsgenie_api_integration" "prometheus_bar" {
  name               = "Prometheus_Bar"
  type               = "Prometheus"
}
```

### Expected Behavior
1. Terraform must not update `opsgenie_api_integration.prometheus_foo` on the second `terraform apply`.
2. `allow_write_access` must be set to `true` by default for `opsgenie_api_integration.prometheus_bar` and `alertmanager` must be able to create alerts in OpsGenie.

### Actual Behavior
1. Terraform tries to update `opsgenie_api_integration.prometheus_foo`, since `allow_write_access == false`:
```
  # opsgenie_api_integration.prometheus_foo will be updated in-place
  ~ resource "opsgenie_api_integration" "prometheus_foo" {
      ~ allow_write_access     = false -> true
        api_key                = (sensitive value)
        enabled                = true
        id                     = "<<uuid>>"
        name                   = "Prometheus_Foo"
        suppress_notifications = false
        type                   = "Prometheus"
    }
```
2. `alertmanager` gets `API Key is not granted with write access` error from OpsGenie, when it tries to send notification.

### Steps to Reproduce
Described above.

**Comment by ffahri** [comment]
Thank you @AlexeyShchukinSecurrency  for raising this issue. We should add default=true field as per documentation suggests

**Comment by ffahri** [comment]
This bug happened because our read function looks wrong value. Fix has been implemented and creating a new release now

**Comment by ffahri** [comment]
v0.3.4 released should be ready in 15min

**Comment by AlexeyShchukinSecurrency** [comment]
So fast! Thank you!
