### ISSUE TITLE
Opsgenie API Integration Actions for Statuspage integration

### ISSUE THREAD

**Issue by dinkarbhagia** [opsgenie/terraform-provider-opsgenie#109]
I see an API for integration actions at opsgenie but cant find it if this can be done using terraform provider.

https://docs.opsgenie.com/docs/integration-api#create-a-new-integration-action

**Comment by rohit-h** [comment]
@dinkarbhagia Thanks for reporting. This feature has been merged, and you can find it in the latest release 👍 
Do note that all action-types for one integration are handled in a single resource, so any existing integration_action that is not perfectly mapped in Terraform will be overwritten. (Do verify via terraform-plan before applying)
