### ISSUE TITLE
opsgenie_schedule deletion fails precondition check

### ISSUE THREAD

**Issue by aduric** [opsgenie/terraform-provider-opsgenie#120]
### Terraform Version
v0.12.24

### Affected Resource(s)
- opsgenie_schedule

### Terraform State
```javascript
    {
      "mode": "managed",
      "type": "opsgenie_schedule",
      "name": "primary",
      "provider": "provider.opsgenie",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "The primary schedule",
            "enabled": true,
            "name": "Primary",
            "timezone": "America/New_York"
          }
        }
      ]
    },
    {
      "mode": "managed",
      "type": "opsgenie_team_routing_rule",
      "name": "primary",
      "provider": "provider.opsgenie",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "criteria": [
              {
                "conditions": [],
                "type": "match-all"
              }
            ],
            "name": "Primary routing rule",
            "notify": [
              {
                "name": "Primary",
                "type": "schedule"
              }
            ],
            "order": 0,
            "time_restriction": [],
            "timezone": "America/New_York"
          },
          "dependencies": [
            "opsgenie_schedule.primary"
          ]
        }
      ]
    }
```

### Terraform Configuration Files
```hcl
resource "opsgenie_team_routing_rule" "primary" {
  name    = "Primary routing rule"
  team_id = data.opsgenie_team.team.id
  order   = 0

  notify {
    type = "none"
  }
}
```

Running the configuration against the state yields:

```
  # opsgenie_schedule.primary will be destroyed
  - resource "opsgenie_schedule" "primary" {
      - description   = "The primary schedule" -> null
      - enabled       = true -> null
      - id            = "<GUID>" -> null
      - name          = "Primary" -> null
      - owner_team_id = "<GUID>" -> null
      - timezone      = "America/New_York" -> null
    }

  # opsgenie_team_routing_rule.primary will be updated in-place
  ~ resource "opsgenie_team_routing_rule" "primary" {
        id       = "<GUID>"
        name     = "Primary routing rule"
        order    = 0
        team_id  = "<GUID>"
        timezone = "America/New_York"

        criteria {
            type = "match-all"
        }

      ~ notify {
            id   = "<GUID>"
            name = "Primary"
          ~ type = "schedule" -> "none"
        }
    }
```

### Expected Behavior
- Should have updated the Routing Rule from "schedule" type to "none"
- Should have removed the Schedule

### Actual Behavior
```
Error: Error occurred with Status code: 428, Message: Schedule cannot be modified. Please remove it from teams: [Team], Took: 0.160000, RequestId: <GUID>
```

### Steps to Reproduce
1. `terraform apply`

I think that in order to remove the Schedule, the Routing Rule has to be updated first, which doesn't seem to be the case based on the output above. Also, when checking the UI, the Routing Rule was still targeting the Schedule, so it seems that the Schedule deletion was attempted and failed before the Routing Rule was changed.

**Comment by ffahri** [comment]
Hey you have to set notify, it seems your schedule still active in team routing rule (because its failed and therefore schedule still in the routing rule field) 

You can reopen issue if you have additional questions

**Comment by aduric** [comment]
@ffahri I changed `notify` to `none` in the routing rule. Also just occurred to me, why does the `notify` field still have the schedule in the plan? Plan for the notify field should be:
```
      ~ notify {
          - id   = "<GUID>"
          - name = "Primary"
          ~ type = "schedule" -> "none"
        }
```
Since there is no schedule now. Or am I missing the correct way to do this?

**Comment by ffahri** [comment]
I reproduced the samething teamrouting rule could not be updated and therefore it cannot delete schedule thats why i closed this issue.
In your case can you confirm routing rule successfully updated to none? 
If so it may be the problem in notify type

**Comment by aduric** [comment]
The routing rule did not update to `none`. Why do you think the routing rule was not able to be updated? Is there an existing issue for this?

**Comment by ffahri** [comment]
notify {
    type = "none"
  }

I changed routing rule to None and deleted schedule via terraform without any problem is there any speficif error you encounter while doing it ?

**Comment by aduric** [comment]
I got the `Schedule cannot be modified` error. The schedule could not be deleted since it was still being referenced by the routing rule. What plan did you get with the latest attempt?
