### ISSUE TITLE
terraform plan always shows timezone change

### ISSUE THREAD

**Issue by mrajeshh** [opsgenie/terraform-provider-opsgenie#143]
Hi there,

Terraform plan for some of the opsgenie resouces always printing timezone change even of it is configured properly in the previous run

### Terraform Version
```
Terraform v0.12.29
+ provider.opsgenie v0.3.7
```

### Affected Resource(s)
Please list the resources as a list:
- opsgenie_user
- opsgenie_schedule
- opsgenie_team_routing_rule

Observed this issue in above resources but it might present in any other resources as well.
 
### Expected Behavior
What should have happened?
It should not have any change with respect to timezone
  ```hcl
~ resource "opsgenie_schedule" "prod" {
        description   = "RescueRangers team production schedule"
        enabled       = true
        id            = "xxxxxxxx"
        name          = "Team_prod_schedule"
        owner_team_id = "xxxxxxxxx"
       timezone      = "Canada/Pacific"
    }
```

### Actual Behavior

In terraform plan and apply it always showing change from `"America/Los_Angeles" -> "Canada/Pacific"`
What actually happened?
  ```hcl
~ resource "opsgenie_schedule" "prod" {
        description   = "RescueRangers team production schedule"
        enabled       = true
        id            = "xxxxxxxx"
        name          = "Team_prod_schedule"
        owner_team_id = "xxxxxxxxx"
      ~ timezone      = "America/Los_Angeles" -> "Canada/Pacific"
    }
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Try to create user in opsgenie with timezone specified in the resource definition
```hcl
resource "opsgenie_user" "this" {
  username  = "abc@opsgenie.com"
  full_name = "ABC"
  role      = "User"
  locale    = "en_CA"
  timezone  = "Canada/Pacific"
}
```
Run `terraform apply` twice to reproduce the issue

**Comment by ffahri** [comment]
Hey @mrajeshh , Opsgenie API will return different timezone even if same GMT or UTC. 
Such as Canada/Pacific = America/Los_Angeles (UTC-7:00). I created a internal ticket about this situation, will update here as well

We may change the internal of Terraform such as if UTC is same set Opsgenie return format etc.
