### ISSUE TITLE
opsgenie_integration_action resource has incorrect capitalization

### ISSUE THREAD

**Issue by jdmulloy** [opsgenie/terraform-provider-opsgenie#148]
![opsgenie_terraform](https://user-images.githubusercontent.com/3395292/89547925-5e19a900-d7d4-11ea-931f-f13580f72c1c.png)

The opsgenie_integration_action resource is missing filter field options I need for AWS SNS like 'eventType' and it also incorrectly has all the fields as all lower case, which means the filters show up incorrectly in the Opsgenie UI.

The following code produced what you see in the screenshot.
```
resource "opsgenie_integration_action" "default_actions" {
  integration_id = opsgenie_api_integration.integration.id

  create {
    name = "Create Action"
    user = "AmazonSns"
    alias = "{{ Subject.substringAfter(\"ALARM:\") }}"
    source = "{{source}}"
    message = "[AmazonSns] {{Subject}}"
    description = "{{Message}}"
    entity = "{{entity}}"

    filter {
      type = "match-all-conditions"
      conditions {
        field = "Subject"
        operation = "contains"
        expected_value = "ALARM:"
      }
      conditions {
        field = "subject"
        operation = "contains"
        not = true
        expected_value = "OK:"
      }
# eventType not suported by opsgenie terraform provider
#      conditions {
#        field = "eventType"
#        operation = "equals"
#        expected_value = "create"
#      }
    }
  }
}
```

**Comment by zonArt** [comment]
True, please implement the eventType field

**Comment by zonArt** [comment]
Not sure if https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/58 is enough, I'm not that confident in my go skills and I probably missed a lot of stuff and don't have the global picture, but it's a first step.

**Comment by avivek** [comment]
Is this something that is in the plans for a release??
We are also blocked by this, where in any filters that we add for SNS is not coming up in OpsGenie.

**Comment by zonArt** [comment]
Hi,

I'm not sure this is fully solved, casing is still wrong. The PR I proposed (opsgenie/opsgenie-go-sdk-v2#58) was taking into account the casing for Message and Subject plus it added also the TopicArn and Timestamp param which are available for SNS integration. Why was is not considered?

**Comment by ffahri** [comment]
Hey internal ticket created for casing it should be validated on api side. 
This issue is autoclosed we also have an internal ticket for casing as well we are following using that.
0.4.4 added the eventType and it seems casing will be fixed soon without updating the provider
Thank you for the contribution @zonArt

**Comment by avivek** [comment]
@ffahri 
It makes sense that the casing issue is  being fixed at the API level.
But how do we track it and know when the same is fixed??
And is there a tentative time, i.e days vs weeks vs months??

**Comment by zonArt** [comment]
Don't know if it's the structure you want to give to the SDK but in case it can be useful, I rebase my branch on master and solve the conflicts so feel free to keep it if happy with it, I've also added two more fields not yet supported by the API (Timestamp and TopicArn)

**Comment by ffahri** [comment]
After discussion with @metehanozturk we thought deleting validation from sdk is much nicer approach since there are a lot of integrations and a lot of custom fields.
https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/66

I'll release new version of the provider today

**Comment by ffahri** [comment]
v0.4.5 released will be available in 30min

If your integration type expects some fields as case sensitive naming such as `Message` in AmazonSns you have to set your field `Message`
