### ISSUE TITLE
Support for other integrations - AWS SNS, NodePing

### ISSUE THREAD

**Issue by avivek** [opsgenie/terraform-provider-opsgenie#153]
We use ops genie and we are exploring using terraform to automate this along with the AWS environment creation.
We were using SNS incoming integration to create alerts and we were also using the Jira integration to create issues and such.

Are custom integrations, like SNS, Jira, Nodeping, something we can support from terraform.

**Comment by ffahri** [comment]
Hey @avivek we are supporting the integrations listed here 
https://docs.opsgenie.com/docs/integration-types-to-use-with-api

**Comment by avivek** [comment]
Thanks a lot. 
It works as expected.
