### ISSUE TITLE
Support custom roles creation

### ISSUE THREAD

**Issue by zonArt** [opsgenie/terraform-provider-opsgenie#161]
Hi,

Thanks for this provider, do you plan to make it possible to create custom roles with it?

**Comment by ffahri** [comment]
Hey, yes we have an user role api and can add this into the provider as well

**Comment by zonArt** [comment]
Yes I saw that it was available in the SDK, thus opening this issue. I'm working on an implementation for it, will submit a PR pretty soon

**Comment by davidvasandani** [comment]
@zonArt have you made any progress on the PR? We'd be glad to help QA it if needed.

**Comment by djmgit** [comment]
Hi, I would like to work on this issue if no else is working right now on this :)

**Comment by ffahri** [comment]
@zonArt Are you planning to create a PR if not we can assign this issue ^

**Comment by zonArt** [comment]
Ouch, really sorry, yes I have tried to begin working on this then I realized there are probably a lot of more skilled people than me to do the job. Sorry for having said I'll do it
