### ISSUE TITLE
Most name attribute allow spaces.

### ISSUE THREAD

**Issue by gfl-chris** [opsgenie/terraform-provider-opsgenie#17]
Thank you for updating the provider! I've been importing OpsGenie state into terraform and came across this: We have some OpsGenie resources that include spaces in their names, for example a team named "Foo Bar" and a schedule named "Foo Bar." 

### Terraform Version
Terraform v0.11.14
+ provider.aws v2.24.0
+ provider.opsgenie v0.2.0
+ provider.template v2.1.2

### Affected Resource(s)
- opsgenie_team
- opsgenie_schedule

### Terraform Configuration Files
```hcl
resource "opsgenie_team" "foo-bar" {
  name = "Foo Bar"
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The expected behaviour is that planning proceeds without any errors as OpsGenie allows spaces in names.

### Actual Behavior
This :point_up: version of the provider errors out during planning (to verify the results of the import):
```
Error: opsgenie_team.foo-bar: only alpha numeric characters and underscores are allowed in "name": "Foo Bar"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import ...`
2. `terraform plan`

### Important Factoids
n/a

### References
n/a

**Comment by gfl-chris** [comment]
See #18

**Comment by ffahri** [comment]
Released thank you
