### ISSUE TITLE
Impossible to create several types of api integrations with the provider

### ISSUE THREAD

**Issue by zonArt** [opsgenie/terraform-provider-opsgenie#176]
Hi,

The following integrations cannot be created with this provider:
- mattermost integration
- solarwinds
- zabbix

### Terraform Version
Terraform v0.12.29
+ provider.opsgenie v0.4.7

### Affected Resource(s)
- opsgenie_api_integration

### Terraform Configuration Files
```hcl
resource "opsgenie_api_integration" "mattermost" {
  name    = "Mattermost"
  type    = "Mattermost"
  enabled = true
}

resource "opsgenie_api_integration" "zabbix" {
  name    = "Zabbix"
  type    = "Zabbix"
  enabled = true
}

resource "opsgenie_api_integration" "solarwinds" {
  name    = "Solarwinds"
  type    = "Solarwinds"
  enabled = true
}
```

### Debug Output
```
Error: Error occurred with Status code: 422, Message: Property [url] cannot be empty., Took: 0.003000, RequestId: 98e812b3-2eb7-442d-afc2-47fad4d4b45b
  on api_integrations.tf line 251, in resource "opsgenie_api_integration" "mattermost":
 251: resource "opsgenie_api_integration" "mattermost" {

Error: Error occurred with Status code: 422, Message: Either sendViaOEC or sendViaMarid should be selected., Took: 0.008000, RequestId: 174031ac-fcc4-46dd-9550-460708747463
  on api_integrations.tf line 144, in resource "opsgenie_api_integration" "zabbix":
 144: resource "opsgenie_api_integration" "zabbix" {

Error: Error occurred with Status code: 422, Message: Either sendViaOEC or sendViaMarid should be selected., Took: 0.009000, RequestId: ab565b92-2d44-43b0-89c2-7bc8c55a6ce6
  on api_integrations.tf line 201, in resource "opsgenie_api_integration" "solarwinds":
 201: resource "opsgenie_api_integration" "solarwinds" {
```

### Expected Behavior
integration successfully created

### Actual Behavior
Failed with above mentioned errors

### Steps to Reproduce
1. `terraform apply`

**Comment by zonArt** [comment]
The expected params are not supported by the provider or I failed to understand how to pass them

**Comment by zonArt** [comment]
Looks like this is partially solved by #197 (for the Mattermost integration at least). Thank you @djmgit 
I still have issue with the zabbix (and solarwinds) ones

**Comment by zonArt** [comment]
Sorry for the person needing to create integration for zabbix or solarwind but as I don't have this need anymore I'll close this issue

**Comment by mcbrineellis** [comment]
I am having the same issue that @zonArt described, so I am opening this issue up again.

When I try and create a resource of type Zabbix, for example:
```
resource "opsgenie_api_integration" "zabbix" {
  name = "zabbixintegration"
  type = "Zabbix"
}
```

I am getting this error:
```
Error: Error occurred with Status code: 422, Message: Either sendViaOEC or sendViaMarid should be selected., Took: 0.019000, RequestId: ebd10a81-e16b-4304-a445-2ca4417b443a
    with opsgenie_api_integration.zabbix,
    on main.tf line 14, in resource "opsgenie_api_integration" "zabbix":
    14: resource "opsgenie_api_integration" "zabbix" {

```
I _was_ able to add the integration myself by talking directly to the API with this JSON, so it's probably just a matter of adding the required boolean arguments (**sendViaMarid** and **sendViaOEC**) to the Terraform provider and it should work:

```
POST https://api.opsgenie.com/v2/integrations HTTP/1.1
Authorization: GenieKey ********-****-****-****-************
Content-Type: application/json

{
    "type": "Zabbix",
    "name": "zabbixintegration",
    "sendViaMarid": false,
    "sendViaOEC": true
}
```
Returned `HTTP/1.1 201 Created` :)

**Comment by mcbrineellis** [comment]
@zonArt , I don't have permission to re-open, would you be able to help me out here?

Thanks!

**Comment by mcbrineellis** [comment]
Please disregard - I opened my own issue :)  noob stuff!
