### ISSUE TITLE
webhook integration fails

### ISSUE THREAD

**Issue by vipinmadhav90** [opsgenie/terraform-provider-opsgenie#181]
Hi there,

I am trying to create webhook integration from terraform and it fails,

### Terraform Version
$ terraform version

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/terraform-providers/opsgenie v0.4.8

### Affected Resource(s)
opsgenie_api_integration

### Terraform Configuration Files
```hcl
resource "opsgenie_api_integration" "api-integration-webhook" {
  name = "test1-Webhook"
  owner_team_id = opsgenie_team.test1.id
  type = "Webhook"

  enabled                        = true
  allow_write_access             = false
  ignore_responders_from_payload = false
  suppress_notifications         = false
}
```

### Debug Output
Error: Error occurred with Status code: 422, Message: Property [url] cannot be empty., Took: 0.294000, RequestId: 414cf592-90b4-4fc1-bbdc-ad0346d9c772

  on main.tf line 11, in resource "opsgenie_api_integration" "api-integration-webhook":
  11: resource "opsgenie_api_integration" "api-integration-webhook" {

### Panic Output
Error: Error occurred with Status code: 422, Message: Property [url] cannot be empty., Took: 0.294000, RequestId: 414cf592-90b4-4fc1-bbdc-ad0346d9c772

  on main.tf line 11, in resource "opsgenie_api_integration" "api-integration-webhook":
  11: resource "opsgenie_api_integration" "api-integration-webhook" {

### Expected Behavior
Create a webhook integration

### Actual Behavior
Error

### Steps to Reproduce
Try to create a webhook integration from terraform

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/api_integration
https://docs.opsgenie.com/docs/webhook-integration

**Comment by ffahri** [comment]
webhook support is available at v0.5.5
