### ISSUE TITLE
Add ignore action to opsgenie_integration_action

### ISSUE THREAD

**Issue by mmsepyx** [opsgenie/terraform-provider-opsgenie#192]
I would like to request the following feature.

In opsgenie integration, you can add 5 action types which are 
- Ignore
- Create Alert
- Close Alert
- Acknowledge Alert
- Add Note

Unfortunately in provider's documentation we can notice that the ignore action is not supported. This is a missing feature.

### Terraform Version
Terraform v0.13.5
provider.opsgenie v0.5.1

### Affected Resource(s)
opsgenie_integration_action

### Terraform Configuration Files
For example the config file:

```hcl
resource "opsgenie_integration_action" "email-integration-action" {
  integration_id = opsgenie_email_integration.XXX.id

  ignore {    
    name  = "Ignore Condition XYZ"
    order = 1

    filter {
      type = "match-all-conditions"

      conditions {
        field          = "X"
        not            = false
        operation      = "Y"
        expected_value = "Z"
      }      
    }
  }

  create {
    name                           = "Create Alert (fetch all)"
    alias                          = "{{subject}}"
    message                        = "{{subject}}"
    source                         = "{{from_name}}"
    priority                       = "P3"
    order                          =  1
    ignore_responders_from_payload = true
    extra_properties               =  {
      ...
    }

    filter {
      type = "match-all"
    }

    responders {
      id   = data.opsgenie_team.XXX.id
      type = "team"
    }
  }
}

```

### Expected Behavior
Should add an ignore action in addition to the create rule

### Actual Behavior
It's a feature request. Currently not implemented.

**Comment by fbreckle** [comment]
This was implemented in #208
