### ISSUE TITLE
Terraform provider with Opsgenie SDK V2 

### ISSUE THREAD

**Issue by nlamirault** [opsgenie/terraform-provider-opsgenie#2]
Hi,
A few days, i made a fork of the original Opsgenie provider to use your SDK v2
The repository is here : https://github.com/nlamirault/terraform-provider-opsgenie/tree/sdk-v2/opsgenie

I create a PR to the Terraform website to update the description : https://github.com/hashicorp/terraform/pull/21349

Are you going to make your provider official?

**Comment by ffahri** [comment]
Hey as you can check the official repository under terraform-providers Opsgenie is there curently active and uses sdk v2.
Thank you
