### ISSUE TITLE
Cannot set description for opsgenie_alert_policy

### ISSUE THREAD

**Issue by promaty** [opsgenie/terraform-provider-opsgenie#202]
### Terraform Version
v0.13.5

### Affected Resource(s)
- opsgenie_alert_policy

### Terraform Configuration Files
```hcl
resource "opsgenie_team" "test" {
  name                = "test"
}
resource "opsgenie_alert_policy" "test" {
  name                = "test"
  message             = "test message"
  team_id             = opsgenie_team.test.id
  alert_description   = "test description"
}
```

### Expected Behavior
Alert policy is created with Alert description.
Repeated `terraform apply` should not detect any changes.

### Actual Behavior
Alert policy alert description (under "Show advanced fields") sets Description to `{{description}}`
![image](https://user-images.githubusercontent.com/26359933/100764047-3808bc00-33f6-11eb-8e55-fe493db51df0.png)

Repeated execution shows the same intended change as executing the first time:
![image](https://user-images.githubusercontent.com/26359933/100764225-671f2d80-33f6-11eb-9561-4ad433702f89.png)

Setting Description field manually prior to running terraform is also overwritten to `{{description}}` after `terraform apply`

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

**Comment by promaty** [comment]
Also [documentation](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/alert_policy#description) mentions `description` instead of `alert_description`, but this causes an error:

```
An argument named "description" is not expected here.
```

**Comment by promaty** [comment]
Seems that this is an Opsgenie API bug, cannot set it using `curl` either, e.g.
```
curl -X POST 'https://api.opsgenie.com/v2/policies' --header 'Authorization: GenieKey MYKEY' --header 'Content-Type: application/json' --data '{
    "type":"alert",
    "enabled":"false",
    "name":"Test",
    "alertDescription":"test description"
}'
```
Contacting support

**Comment by promaty** [comment]
Actually the correct field for alert description in a policy is "description", but terraform code still uses "alertDescription" in the API request. This seems to work fine:
```
curl -X POST 'https://api.opsgenie.com/v2/policies' --header 'Authorization: GenieKey MYKEY' --header 'Content-Type: application/json' --data '{
    "type":"alert",
    "enabled":"false",
    "name":"Test",
    "description":"test description"
}'
```
I will submit a PR fix later today

**Comment by ffahri** [comment]
v0.6.8 released
