### ISSUE TITLE
Unable to set key in extra-properties field of condition for service incident rule

### ISSUE THREAD

**Issue by mgmuk** [opsgenie/terraform-provider-opsgenie#204]
### Terraform Version
Terraform v0.13.4

### Affected Resource(s)
- opsgenie_service_incident_rule

### Terraform Configuration Files
```hcl
resource "opsgenie_service_incident_rule" "aks-test-eu" {
  service_id = opsgenie_service.aks-test-eu.id
  incident_rule {
    condition_match_type = "match-all-conditions"
    conditions {
      field          = "extra-properties"
      not            = false
      operation      = "equals"
      expected_value = "Test"
    }
    conditions {
      field     = "extra-properties"
      not       = false
      operation = "equals"
      expected_value = "AKS"
    }

    incident_properties {
      message     = "{{message}}"
      description = "{{description}}"
      priority    = "P2"
      stakeholder_properties {
        enable      = true
        message     = "{{message}}"
        description = "{{description}}"
      }
    }
  }
}
```

### Expected Behavior
Service incident rule is created with a condition that matches on the value of a given key in the extra-properties field.
![image](https://user-images.githubusercontent.com/28368113/101653386-2e570800-3a37-11eb-80a5-9140bf8ae095.png)

### Actual Behavior
API returns the following error:
`"Condition fields with [extra-properties] must also define its key in [key]"`
This is because the provider does not allow you to set the key name. An example call to the API that works:
`{
    "conditionMatchType": "match-all-conditions",
    "conditions": [{
        "expectedValue": "AKS",
        "operation": "equals",
        "not": false,
        "field": "extra-properties",
        "key": "Service"
    }],
    "incidentProperties": {
        "message": "Incident Message",
        "description": "Incident Description",
        "tags": ["Tag1", "Tag2"],
        "priority": "P4",
        "stakeholderProperties": {
            "enable": true,
            "message": "Stakeholder Message",
            "description": "Stakeholder Description"
        }
    }
}`

### Steps to Reproduce
1. `terraform apply`

**Comment by ilteristabak** [comment]
fixed with #205, you can update provider version to 0.5.4
