### ISSUE TITLE
[Feature Request] Save API key when creating integration

### ISSUE THREAD

**Issue by KevinLoganBS** [opsgenie/terraform-provider-opsgenie#23]
Our company is starting to trial OpsGenie, and we were creating integrations using terraform. We are using a lot of the AWS integrations, but they require subscribing to an SNS topic, which also needs an API key for the subscription.

Looking at [OpsGenie API docs](https://docs.opsgenie.com/docs/integration-api#section-create-api-based-integration), it looks like the `apiKey` is returned only on integration creation.

Would it be possible to store that as an output to pass to other terraform resources?

**Comment by ffahri** [comment]
Thank you for this request i will look into it !
