### ISSUE TITLE
cannot add "group" as participant for opsgenie_schedule_rotation

### ISSUE THREAD

**Issue by TripleA-rocks** [opsgenie/terraform-provider-opsgenie#230]
### Terraform Version
Terraform v0.14.7
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.3

### Affected Resource(s)
opsgenie_schedule_rotation

### Expected Behavior
Being able to update an imported opsgenie_schedule_rotation with participant type = group, because terraform import, imported the participant with type = group.

### Actual Behavior
Error: it can only be one of these 'user', 'schedule', 'team', 'escalation'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. import existing opsgenie_schedule_rotation that has participant type = group
2. terraform plan

**Comment by ulisse31** [comment]
Facing this issue as well. We would need a way to both define and use "groups" as in the GUI.

**Comment by TripleA-rocks** [comment]
I learnt that the "group" feature is not supported by opsgenie anymore. I did find an workaround and that is to create a new_escalation add the members in there, and add that escalation to the schedule_rotation. It does basically the same thing as the group, but you have to freedom to choose which group_member answers when.
