### ISSUE TITLE
Opsgenie Incoming Call Routing

### ISSUE THREAD

**Issue by zonArt** [opsgenie/terraform-provider-opsgenie#240]
Hi there,

I've got a really basic quick question. Is it possible to set incoming call routing integration with this provider? If yes, what type would you chose and otherwise do you plan to integrate it in the provider soon or later?

Thanks for the information

**Comment by zonArt** [comment]
No one to help me on this one? Can I add any useful information to obtain some help?

**Comment by ffahri** [comment]
hey supported integrations are available in our docs page
https://support.atlassian.com/opsgenie/docs/integration-types-to-be-used-with-the-api/

If the api support is not available for certain types we can't provide it in TF as well.
