### ISSUE TITLE
Support darwin_arm64

### ISSUE THREAD

**Issue by h17liner** [opsgenie/terraform-provider-opsgenie#242]
Hi there,

Could you please make release with support darwin_arm64.

Thanks

**Comment by Vrtak-CZ** [comment]
In first place they will need to update to Go 1.16+

**Comment by ffahri** [comment]
Agree, i'll included this in the teams roadmap. We need to update our dependencies and provide arm build

**Comment by ffahri** [comment]
Hey, we released new version using go1.16
