### ISSUE TITLE
CloudWatch Integration type support

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [opsgenie/terraform-provider-opsgenie#255]
### Terraform Version
Terraform v0.13.5

### Affected Resource(s)
opsgenie_cloudwatch_integration

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
There is none
```

### Debug Output
There is no such thing.

### Panic Output
None

### Expected Behavior
In https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs , opsgenie_cloudwatch_integration should be listed.

### Actual Behavior
It's not there.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Look in docs
2. There does not appear to be a way to configure a cloudwatch opsgenie integration through terraform

### Important Factoids
Nothing special

### References
None, kind of surprised there is already not an open ticket for this.

**Comment by ffahri** [comment]
hey we are using type field for integrations
https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/api_integration#type
```
resource "opsgenie_api_integration" "cw" {
  name = "test"
  type = "Cloudwatch"
  ...
 ```

**Comment by krestivo-kdinfotech** [comment]
Where are the options documented?

**Comment by ffahri** [comment]
https://support.atlassian.com/opsgenie/docs/integration-types-to-be-used-with-the-api/
