### ISSUE TITLE
Status code: 422, Message: Default routing rule can not have timezone.

### ISSUE THREAD

**Issue by JeffAshton** [opsgenie/terraform-provider-opsgenie#264]
When updating a team's default routing rule, the timezone is passed and fails the API request.

### Terraform Version
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.5

### Affected Resource(s)
- opsgenie_team_routing_rule

### Terraform Configuration Files
```hcl
data "opsgenie_team" "test" {
  name = "test"
}

resource "opsgenie_escalation" "test" {
  name          = "Test"
  owner_team_id = data.opsgenie_team.test.id

  rules {
    condition   = "if-not-acked"
    notify_type = "all"
    delay       = 0

    recipient {
      type = "team"
      id   = data.opsgenie_team.test.id
    }
  }
}

resource "opsgenie_team_routing_rule" "test" {
  name    = "Default Routing Rule"
  team_id = data.opsgenie_team.test.id
  order   = 0
  timezone = "America/New_York"

  criteria {
    type = "match-all"
  }

  notify {
    id   = opsgenie_escalation.test.id
    name = opsgenie_escalation.test.name
    type = "escalation"
  }
}
```

### Debug Output

> opsgenie_team_routing_rule.lms_queues: Modifying... [id=588afd74-a1f5-40b8-af89-f797780908cc]
> 
> Error: Error occurred with Status code: 422, Message: Default routing rule can not have timezone., Took: 0.005000, RequestId: 858cd630-92b4-4ed7-9f30-cd9d0994ade5
> 

### Expected Behavior
The `timezone` should not be sent to Team Routing Rule API update call when `isDefault: true` is set on the rule.

### Actual Behavior
The `timezone` is sent in the request and boom!!!

https://github.com/opsgenie/terraform-provider-opsgenie/blob/d98b6d4acdda83a15e6be2e1be8a48d5c75ea01f/opsgenie/resource_opsgenie_team_routing_rule.go#L284

Using `ignore_changes` is insufficient because the refresh pulls the applied timezone from the team:

https://github.com/opsgenie/terraform-provider-opsgenie/blob/d98b6d4acdda83a15e6be2e1be8a48d5c75ea01f/opsgenie/resource_opsgenie_team_routing_rule.go#L257

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Import a default `opsgenie_team_routing_rule` resource
2. Make a change to the notify target
3. Run `terraform apply`

If `timezone` is omitted, then terraform plan will always return a change set.

### Proposed Solution

Only apply the timezone on read when not the default routing rule.

https://github.com/opsgenie/terraform-provider-opsgenie/blob/d98b6d4acdda83a15e6be2e1be8a48d5c75ea01f/opsgenie/resource_opsgenie_team_routing_rule.go#L257

```
if ( !result.IsDefault ) {
    d.Set("timezone", result.Timezone)
}
```

https://github.com/opsgenie/terraform-provider-opsgenie/blob/d98b6d4acdda83a15e6be2e1be8a48d5c75ea01f/vendor/github.com/opsgenie/opsgenie-go-sdk-v2/team/result.go#L21

**Comment by ffahri** [comment]
0.6.6 released thank you for this issue
