### ISSUE TITLE
429, Message: You are making too many requests!

### ISSUE THREAD

**Issue by zonArt** [opsgenie/terraform-provider-opsgenie#268]
Hi there,

### Terraform Version
1.0.8

### Provider Version
v0.6.5

### Affected Resource(s)
All

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Not relevant

### Debug Output
```
│ Error: Error occurred with Status code: 429, Message: You are making too many requests! To avoid errors, we recommend you limit requests., Took: 0.002000, RequestId: 3e3efb60-e916-4ad2-a873-184e092191e0
```

### Panic Output
N/A

### Expected Behavior
Code applies modification to opsgenie

### Actual Behavior
Received a 429 http response because it looks like it's doing to many request

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

**Comment by n-oden** [comment]
This is affecting us as well.

**Comment by zonArt** [comment]
After having contacted opsgenie support, they confirmed to me that they increased the rate limit for all client and that this should not happen anymore. The fix (raising the rate limit) though is not enough IMHO as at a moment of time you could could still need more and I think the provider should handle that gently and perform retries when receiving 429. However I'm not skilled enough to implement that myself

**Comment by ffahri** [comment]
Hey thank you for this issue.
Current code already has the backoff algorithm
```
...
	RetryCount:     10,
	OpsGenieAPIURL: client.ApiUrl(c.ApiUrl),
	Backoff:        retryablehttp.DefaultBackoff,
..
```
I'll check with the go-sdk if this issue persists, or will route this to our internal teams about rate limiting thank you

**Comment by Sebbo94BY** [comment]
Hey,
We are also facing this rate limit issue with the latest OpsGenie Terraform provider `0.6.5`.

This issue has been closed without any reference or feedback about this already implemented backoff algorithm solution, which you wanted to check @ffahri .

So what's the status of this issue?

Can we expect a newer version of the Terraform provider with a respective workaround / fix?

Do we need to contact the OpsGenie support for requesting a higher API limit?

**Comment by ffahri** [comment]
Hey provider already has the backoff algorithm using go-sdkv2
https://github.com/opsgenie/terraform-provider-opsgenie/blob/master/opsgenie/config.go#L24

I think its best to contact with support for this case since it might related to Account

**Comment by Sebbo94BY** [comment]
Yes, I know, but it's unfortunately still randomly failing with the latest OpsGenie provider `0.6.7`. :(

We have also already contacted the OpsGenie support to increase our API rate limits, but we are already at the highest possible settings for our OpsGenie plan:

> I heard back from our Development Team and they instructed that the API Limit cannot be increased manually and as of now it is already at 45 per second and 606 per minute limitation for your configuration APIs and the only way to increase it is by subscribing to more licenses as that defines your account's API Rate Limits.

**Comment by ffahri** [comment]
Understand, let me create an issue for us to allow users to configure retry and backoff duration for Opsgenie client 👍

**Comment by iuriaranda** [comment]
> Understand, let me create an issue for us to allow users to configure retry and backoff duration for Opsgenie client +1

We're also hitting Opsgenie rate limits quite hard ourselves. We're managing a lot of different integrations through the same Terraform stack and refreshing the state on every plan or apply fails because of the rate limit. The backoff mechanism is definitely kicking in, as the last resources are definitely slower to refresh, but that's not enough as some of the last resources always fail to refresh. Are there any plans of making that backoff mechanism settings configurable?

**Comment by iuriaranda** [comment]
I've opened a PR to make the retry mechanism configurable: https://github.com/opsgenie/terraform-provider-opsgenie/pull/296

**Comment by apsamuel** [comment]
I'm still running into this; it blocks the running of `plan` or `apply` to update our OpsGenie configurations.

Things to note:

- we specifically want to use multiple integration actions
- there doesn't seem to be a way to control any delays or backoff settings.
- literally can not change my opsgenie setup.

```
opsgenie_service_incident_rule.noop[13]: Refreshing state... [id=c3d75ad2-94d0-4359-8a7d-33a4ef86e479]
opsgenie_service_incident_rule.noop[11]: Refreshing state... [id=8c2ce74e-d4f7-4982-bf75-b06c3ae2d34a]
opsgenie_service_incident_rule.noop[7]: Refreshing state... [id=4ce42090-3772-4fa6-ae43-4e85c7b39184]
opsgenie_service_incident_rule.noop[6]: Refreshing state... [id=060fd85f-9088-40a8-8878-6f1a84c4ec42]
opsgenie_service_incident_rule.noop[8]: Refreshing state... [id=0023111f-4bef-4ea1-b580-507ddaefb1d1]
opsgenie_service_incident_rule.noop[10]: Refreshing state... [id=00cc51d4-f603-44b3-94a7-e7f620a4a9e4]
opsgenie_service_incident_rule.noop[2]: Refreshing state... [id=05d5a377-db31-4478-ab24-af167615b7a4]
opsgenie_service_incident_rule.noop[3]: Refreshing state... [id=e673a9bc-6e16-4f29-9c14-d666cac30d1a]
opsgenie_service_incident_rule.noop[5]: Refreshing state... [id=20ba695f-0117-4e89-a3fb-022556d42472]
opsgenie_service_incident_rule.noop[0]: Refreshing state... [id=0ad73cd6-7e17-4c28-9eda-f191594707f4]
opsgenie_service_incident_rule.noop[1]: Refreshing state... [id=8c4f7625-1d10-48d0-a259-8bb2e04343dc]
opsgenie_service_incident_rule.noop[4]: Refreshing state... [id=4e14b70b-9b53-439f-b938-c64576d7b3fd]
opsgenie_service_incident_rule.noop[12]: Refreshing state... [id=bca31edf-9a60-4c3d-b441-bab2ae100562]
opsgenie_service_incident_rule.noop[9]: Refreshing state... [id=0a182bc7-be7c-445d-80d5-d0714e4254ab]
                                                                                                                                                                           
╷                                                                                                                                                                          
│ Error: Error occurred with Status code: 429, Message: You are making too many requests! To avoid errors, we recommend you limit requests., Took: 0.001000, RequestId: e3e
a0573-3c5e-45d3-bcf7-68e78ca4a37f                                                                                                                                          
│                                                                                                                                                                          
│   with opsgenie_integration_action.noop[3],                                                                                                                              
│   on main.tf line 119, in resource "opsgenie_integration_action" "noop":                                                                                                 
│  119: resource "opsgenie_integration_action" "noop" {                                                                                                                    
│                                                                 
```

 using 

```
Terraform v1.2.7
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```
