### ISSUE TITLE
Provider not usable on Apple Silicon

### ISSUE THREAD

**Issue by padraic-padraic** [opsgenie/terraform-provider-opsgenie#274]
### Terraform Version
terraform v1.0.11, darwin_arm64

### Affected Resource(s)
The opsgenie provider

### Panic Output
```
Error: Incompatible provider version
│
│ Provider registry.terraform.io/opsgenie/opsgenie v0.6.5 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

### Expected Behavior
The provider is compatible with darwin_arm64

### Actual Behavior
What actually happened?

### Steps to Reproduce
1. Create small config loading the opsgenie provider
```hcl
terraform {
  required_providers {
    opsgenie = {
      source = "opsgenie/opsgenie"
      version = "0.6.5"
    }
 }
}
```
2. Run `terraform init`

### Important Factoids
darwin_arm64 is a supported platform with Go 1.16 and up. The github actions used to release this provider however still use Go 1.14. I submitted a PR, #272, to update the actions.

**Comment by ffahri** [comment]
Hey, we released new version using go1.16
