### ISSUE TITLE
Add stakeholders to api integration resources

### ISSUE THREAD

**Issue by nitrocode** [opsgenie/terraform-provider-opsgenie#278]
It looks like stakeholders is missing from these resources

* [opsgenie_api_integration](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/api_integration)
* [opsgenie_integration_action](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/integration_action)

But it looks like it can be set in the UI

![image](https://user-images.githubusercontent.com/7775707/145457043-92bf7a7f-02b4-4857-b2e4-44dc44179996.png)

In the following resources, it looks like stakeholder properties can be supplied but we cannot add individual users

* [opsgenie_service_incident_rule](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/service_incident_rule#stakeholder_properties)
* [opsgenie_incident_template](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/incident_template)

Here is the opsgenie API for it so it's definitely possible. I suppose we just need an `opsgenie_service_audience_template` resource.

https://docs.opsgenie.com/docs/service-audience-template-api#stakeholder-fields

**Comment by koushik-swaminathan** [comment]
Currently, adding or updating users as stakeholders are not supported in any of the [public APIs](https://docs.opsgenie.com/docs) for the above-mentioned resources. Therefore, we would not be able to support the addition of stakeholders through these resources in Terraform. The addition of stakeholders through the UI is a part of the Service functionality. API integration and Integration Actions are different functionalities. Service Incident Rule and Incident Template support only stakeholder properties even through the UI and not the addition of stakeholders themselves. We can however look into adding the support for Audience Template. It'd be great if you could raise a feature request for the same here: https://support.atlassian.com/contact/
