### ISSUE TITLE
Issues with Ordering of Team Members

### ISSUE THREAD

**Issue by jharrison-quantium** [opsgenie/terraform-provider-opsgenie#288]
### Terraform Version
terraform v1.1.3
opsgenie/opsgenie v0.6.8 (also confirmed with 0.6.9, 0.6.10 and reported with 0.6.2)

### Affected Resource(s)
- opsgenie_team

### Expected Behavior
For a plan after an apply, there should be no changes.

### Actual Behavior
Since yesterday. When doing a `terraform plan` it's showing required changes in the order of the member list. running a terraform apply will "apply" these changes, but further terraform plan operations still required changes in this ordering.

### Steps to Reproduce
1. Create HCL describing a team with more than one member
2. `terraform apply`
3. `terraform plan` - this should show no required changes.

### Important Factoids
* This appears to be because the order of the members presented by opsgenie is unstable - the actual change required in the ordering changes each time you plan, suggesting that the issue is caused by instability upstream. 
* This started on or around 9th Feb 2022
* This happens with older versions of terraform - so it's not a change in terraform which has caused this issue
* This did not happen previously with v0.6.8 of the provider

**Comment by tyrken** [comment]
FWIW we're hitting the same problem, but are still back on v0.6.2 of the provider (and terraform v0.14.11).  Agree on your suggestion of a change in the upstream web API occuring around the 9th Feb.

**Comment by jharrison-quantium** [comment]
Retested with version 0.6.9 - issue still occurs

**Comment by fnuva** [comment]
Thank you for the input. version 0.6.9 fixes the import problem in routing order.  PATCH request doesn't accept the Order field for routing rules. Although `terraform apply` , the update does not works for order. 
We will  use change_order request in update actions in following releases and fix it.

**Comment by jharrison-quantium** [comment]
Confirming this issues is not fixed in 0.6.10

**Comment by nayoa** [comment]
We're also getting this in v0.6.4 & Terraform v1.0.11

**Comment by b3rgman** [comment]
Seeing this in 0.6.9 with terraform version v1.1.6

**Comment by fishfacemcgee** [comment]
> Thank you for the input. version 0.6.9 fixes the import problem in routing order. PATCH request doesn't accept the Order field for routing rules. Although `terraform apply` , the update does not works for order. We will use change_order request in update actions in following releases and fix it.

@fnuva Just to be clear, the ordering of `member` arguments in an `opsgenie_team` resource is a routing order? Like an implicit one? I want to make sure I'm understanding the issue you're describing as it relates to this specific GH issue.

**Comment by tdfacer** [comment]
Seeing this on `0.6.10` w/ Terraform version `1.1.8`. I see https://github.com/multani/terraform-provider-opsgenie/pull/1 has just recently been opened, hopefully that will do the trick!

**Comment by multani** [comment]
Hopefully https://github.com/opsgenie/terraform-provider-opsgenie/pull/298 gets merged too ;)

**Comment by fantom0005** [comment]
Hi, guys! Why will we not merge this fix? https://github.com/opsgenie/terraform-provider-opsgenie/pull/298

The terraform provider has a bug from February. This is a very long time, given that there is already the pull request with a fix.

**Comment by bateller** [comment]
Teams is completely broken until https://github.com/opsgenie/terraform-provider-opsgenie/pull/318 is merged and a new release is built. 

The PR for this issue https://github.com/opsgenie/terraform-provider-opsgenie/pull/298 did not fully resolve this issue

**Comment by bateller** [comment]
https://github.com/opsgenie/terraform-provider-opsgenie/pull/318 is now merged, and a tag was added with the changes [v0.6.12](https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.12).

Just waiting on a new [release](https://github.com/opsgenie/terraform-provider-opsgenie/releases) with updated binaries

**Comment by bateller** [comment]
New release with binaries finally: https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.14
