### ISSUE TITLE
Every plan shows `opsgenie_alert_policy` shows unset `alert_description` changing to `null`

### ISSUE THREAD

**Issue by nitrocode** [opsgenie/terraform-provider-opsgenie#290]
### Terraform Version

terraform v1.1.3
opsgenie v0.6.8

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_alert_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "opsgenie_alert_policy" "this" {
  # no alert_description is set
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
It should plan without showing any change by defaulting the unset `alert_description` to `{{description}}` instead of `null` if it's unset

### Actual Behavior
Every plan shows the following change

```hcl
  ~ resource "opsgenie_alert_policy" "this" {
      - alert_description          = "{{description}}" -> null
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
N/A

### References
* Upstream module fix to prevent constant plans https://github.com/cloudposse/terraform-opsgenie-incident-management/pull/29

**Comment by arjunrajpal** [comment]
This has been fixed in [v0.6.25](https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.25).
