### ISSUE TITLE
How import Heartbeat

### ISSUE THREAD

**Issue by nlamirault** [opsgenie/terraform-provider-opsgenie#30]
Hi there,
How import Heartbeat ?
According to the documentation we must provide the `id`, but Opsgenie API don't return the ID  : https://docs.opsgenie.com/docs/heartbeat-api#section-get-heartbeat-request

**Comment by ffahri** [comment]
Hey yes, api does not return id for heartbeats. I set name=id for provider. heartbeats names are unique. 
you can use the following 

```$terraform import opsgenie_heartbeat.test2 heartbeatname

opsgenie_heartbeat.test2: Importing from ID "heartbeatname"...
opsgenie_heartbeat.test2: Import complete!
  Imported opsgenie_heartbeat
opsgenie_heartbeat.test2: Refreshing state... [id=heartbeatname]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
