### ISSUE TITLE
opsgenie integration fail

### ISSUE THREAD

**Issue by davypouillie** [opsgenie/terraform-provider-opsgenie#303]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:

    resource "opsgenie_api_integration"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "opsgenie_api_integration" "sclrcloudwatch" {
  name                   = format("%s_CloudWatch", var.project)
  type                   = "CloudWatch"
  owner_team_id          = opsgenie_team.sclrteam.id
  enabled                = true
  allow_write_access     = false
  suppress_notifications = false

  responders {
    type = "team"
    id   = opsgenie_team.sclrteam.id
  }

}

### Debug Output
│ Error: Error occurred with Status code: 404, Message: No handler found, Took: 0.001000, RequestId: 8e7be1ab-a1e7-42a3-a3d0-064a546e850e
│ 
│   with opsgenie_api_integration.sclrcloudwatch,
│   on main.tf line 185, in resource "opsgenie_api_integration" "sclrcloudwatch":
│  185: resource "opsgenie_api_integration" "sclrcloudwatch" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- None

**Comment by Zebradil** [comment]
Hey @davypouillie,
I see the same error. Did you solve this?

**Comment by Zebradil** [comment]
We managed to fix the issue by changing the API URL:
```diff
-  api_url = "api.eu.opsgenie.com"
+  api_url = "api.opsgenie.com"
```
I have no idea, what happened on the Opsgenie's side, but now that works.

**Comment by davypouillie** [comment]
@Zebradil , it was the same solution for me….one day it was working on the eu api url. The day after it was not working anymore. Very strange because our Opsgenie is deployed in the eu region.
