### ISSUE TITLE
Missing arm64 build

### ISSUE THREAD

**Issue by kpocius** [opsgenie/terraform-provider-opsgenie#317]
0.6.11 release is missing arm64 build. It was removed in this commit https://github.com/opsgenie/terraform-provider-opsgenie/commit/a7efe767e015f6822ddee8b6711bf3185c1076d9 -- was that deliberate and if so, what was the reason behind this choice? Can we expect arm64 support or will we have to build the provider ourselves from now on? 🤔

**Comment by wyardley** [comment]
Getting an error related to this as well
```
Initializing provider plugins...
- Finding latest version of datadog/datadog...
- Finding opsgenie/opsgenie versions matching "0.6.11"...
- Finding latest version of hashicorp/google...
- Using previously-installed datadog/datadog v3.14.0
- Using previously-installed hashicorp/google v4.29.0
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/opsgenie/opsgenie v0.6.11 does not have a package
│ available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are
│ available for all platforms. Other versions of this provider may have different
│ platforms supported.
```

**Comment by wyardley** [comment]
@fnuva @multani is this change known / intentional?

**Comment by multani** [comment]
@wyardley not my fault this time :sweat_smile: 

But I think this was changed due to https://github.com/opsgenie/terraform-provider-opsgenie/runs/7466625010

> failed to build for windows_arm64: exit status 2: cmd/go: unsupported GOOS/GOARCH pair windows/arm64

I would say it's probably due to an old version of Golang: the provider still uses Go 1.16 but this architecture pair is available since [1.17](https://go.dev/doc/go1.17).

**Comment by wyardley** [comment]
Ahah thanks. Saw the note about one more change and the commit removing arm was on the changelog commit adding an item for your change, so wasn’t sure if there was some connection.

**Comment by debayande** [comment]
~Could someone build this one manually and distribute, please? Thanks.~

Hold on... can't an:

```
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: arm64
```

directive be thrown in within `.goreleaser.yml`? That'd fix the CI build breakage encountered in https://github.com/opsgenie/terraform-provider-opsgenie/runs/7466625010, wouldn't it (at least till an upgrade path to Go 1.17 can be figured out)?

If this could go out together with @multani's [list ⟶ set changes](https://github.com/opsgenie/terraform-provider-opsgenie/pull/318), then ❤️. ~I'm more than happy to stick in a PR myself if needed.~ Done.

Thanks a million.

**Comment by fnuva** [comment]
Yeah  I just want to release quickly. I will provide you new release for you soon with fix.

**Comment by wyardley** [comment]
Hi all - will the missing build be added and / or a new release published?

**Comment by tjstansell** [comment]
This is still unavailable ... can someone publish a new release or at least get the arm64 build published?
```
#23 268.1 Error: Provider release not available
#23 268.1 
#23 268.1 Failed to download registry.terraform.io/opsgenie/opsgenie v0.6.11 for
#23 268.2 linux_arm64: provider registry.terraform.io/opsgenie/opsgenie 0.6.11 is not
#23 268.2 available for linux_arm64.
```
