### ISSUE TITLE
Issue Running 0.2.3 OpsGenie

### ISSUE THREAD

**Issue by dfoley84-zz** [opsgenie/terraform-provider-opsgenie#32]
Currently seen an error while running the OpsGenie provider: 

Error: Response could not be parsed, invalid character ‘<’ looking for beginning of value

Versions:

Terraform v0.12.7
provider.opsgenie v0.2.3

```
2019-09-27T08:37:36.952Z [DEBUG] plugin: plugin started: path=/home/ubuntu/NewUser/.terraform/plugins/linux_amd64/terraform-provider-opsgenie_v0.2.3_x4 pid=2749
2019-09-27T08:37:36.952Z [DEBUG] plugin: waiting for RPC address: path=/home/ubuntu/NewUser/.terraform/plugins/linux_amd64/terraform-provider-opsgenie_v0.2.3_x4
2019-09-27T08:37:36.964Z [INFO]  plugin.terraform-provider-opsgenie_v0.2.3_x4: configuring server automatic mTLS: timestamp=2019-09-27T08:37:36.964Z
2019-09-27T08:37:37.005Z [DEBUG] plugin.terraform-provider-opsgenie_v0.2.3_x4: plugin address: address=/tmp/plugin478246039 network=unix timestamp=2019-09-27T08:37:37.004Z
2019-09-27T08:37:37.092Z [DEBUG] plugin.terraform-provider-opsgenie_v0.2.3_x4: 2019/09/27 08:37:37 [INFO] Initializing OpsGenie client
2019-09-27T08:37:37.092Z [DEBUG] plugin.terraform-provider-opsgenie_v0.2.3_x4: 2019/09/27 08:37:37 [INFO] OpsGenie client configured
2019-09-27T08:37:37.101Z [DEBUG] plugin.terraform-provider-opsgenie_v0.2.3_x4: 2019/09/27 08:37:37 [INFO] Creating OpsGenie user ''
2019-09-27T08:37:37.124Z [DEBUG] plugin: plugin process exited: path=/home/ubuntu/NewUser/.terraform/plugins/linux_amd64/terraform-provider-opsgenie_v0.2.3_x4 pid=2749
root@instance-1:/home/ubuntu/NewUser# ls
```

`opsgenie_user.first_user - *terraform.NodeValidatableResource
2019/09/27 08:37:32 [TRACE] AttachResourceConfigTransformer: attaching to "opsgenie_user.first_user" (*terraform.NodeValidatableResource) config from main.tf:8,1-38
opsgenie_user.first_user - *terraform.NodeValidatableResource
opsgenie_user.first_user - *terraform.NodeValidatableResource
2019/09/27 08:37:32 [TRACE] ProviderTransformer: opsgenie_user.first_user is provided by provider.opsgenie or inherited equivalent
2019/09/27 08:37:32 [TRACE] ProviderTransformer: exact match for provider.opsgenie serving opsgenie_user.first_user
2019/09/27 08:37:32 [DEBUG] ProviderTransformer: "opsgenie_user.first_user" (*terraform.NodeValidatableResource) needs provider.opsgenie
opsgenie_user.first_user - *terraform.NodeValidatableResource
opsgenie_user.first_user - *terraform.NodeValidatableResource
2019/09/27 08:37:32 [TRACE] AttachSchemaTransformer: attaching resource schema to opsgenie_user.first_user
2019/09/27 08:37:32 [DEBUG] ReferenceTransformer: "opsgenie_team.GTI" references: [opsgenie_user.first_user var.administrator var.user]
2019/09/27 08:37:32 [DEBUG] ReferenceTransformer: "opsgenie_schedule_rotation.test" references: [opsgenie_schedule.GTISchedule opsgenie_user.first_user]
2019/09/27 08:37:32 [DEBUG] ReferenceTransformer: "opsgenie_user.first_user" references: [var.administrator]
  opsgenie_user.first_user - *terraform.NodeValidatableResource
  opsgenie_user.first_user - *terraform.NodeValidatableResource
opsgenie_user.first_user - *terraform.NodeValidatableResource
  opsgenie_user.first_user - *terraform.NodeValidatableResource
  opsgenie_user.first_user - *terraform.NodeValidatableResource
  opsgenie_user.first_user - *terraform.NodeValidatableResource
opsgenie_user.first_user - *terraform.NodeValidatableR`

Ref: https://discuss.hashicorp.com/t/issue-running-opsgenie-provider-with-terraform-0-12-7/3044/4

**Comment by ffahri** [comment]
Hey @dfoley84
i tried to create users on both us and eu api endpoints but didn't recieve any error  (using https://discuss.hashicorp.com/t/issue-running-opsgenie-provider-with-terraform-0-12-7/3044  template )
Did you created any user or every user creation returns the same error ?

**Comment by ffahri** [comment]
The error coming from go-sdk-v2 (https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/f361aa9251b60fabccefe7d9fe7231519e718c88/client/client.go#L553) 
Will look why the response cant be parsed @dfoley84

**Comment by ffahri** [comment]
Hey, @dfoley84 are you still getting these errors?

**Comment by dfoley84-zz** [comment]
@ffahri  will try again

**Comment by dfoley84-zz** [comment]
Error: Response could not be parsed, invalid character '<' looking for beginning of value

  on main.tf line 8, in resource "opsgenie_user" "test":
   8: resource "opsgenie_user" "test"{

**Comment by ffahri** [comment]
Hey @dfoley84 thats may be happen if you write api url to something like `opsgenie.com`

Allowed api urls is without https just below urls
`api.opsgenie.com`
`api.eu.opsgenie.com`

**Comment by ffahri** [comment]
sample provider definition is :
```
provider "opsgenie" {
  api_key = "API-KEY"
  api_url = "api.opsgenie.com"
  version = "0.2.3"
}
```

**Comment by ffahri** [comment]
closing issue feel free to reopen if this reoccurs
