### ISSUE TITLE
opsgenie_integration_action does not set key despite field being set to "extra-properties"

### ISSUE THREAD

**Issue by upstream-dmahlberg** [opsgenie/terraform-provider-opsgenie#322]
### Terraform Version
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.10

### Affected Resource(s)
- opsgenie_integration_action

### Terraform Configuration Files
```hcl
resource "opsgenie_integration_action" "grafana" {
  integration_id = opsgenie_api_integration.grafana.id
  #P1
  create {
    name     = "Create Alert"
    message  = "[Grafana]: {{message}}"
    note     = "{{note}}"
    alias    = "{{monitor_id}}"
    source   = "{{source}}"
    entity   = "{{entity}}"
    priority = "P1"

    filter {
      type = "match-any-condition"
      conditions {
        field          = "extra-properties"
        key            = "severity"
        operation      = "contains"
        expected_value = "critical"
        not            = false
      }
    }
  }
  #P3
  create {
    name     = "Create Alert Warning"
    message  = "[Grafana]: {{message}}"
    note     = "{{note}}"
    alias    = "{{monitor_id}}"
    source   = "{{source}}"
    entity   = "{{entity}}"
    priority = "P3"

    filter {
      type = "match-any-condition"
      conditions {
        field          = "extra-properties"
        key            = "severity"
        operation      = "contains"
        expected_value = "warning"
        not            = false
      }
    }
  }
  #P4 Default Alerts
  create {
    name     = "Create Alert Default"
    message  = "[Grafana]: {{message}}"
    note     = "{{note}}"
    alias    = "{{monitor_id}}"
    source   = "{{source}}"
    entity   = "{{entity}}"
    priority = "P4"

    filter {
      type = "match-all"
    }
  }
  close {
    name  = "Close Alert"
    type  = "close"
    alias = "{{monitor_id}}"
    note  = "{{note}}"
    order = 1

    filter {
      type = "match-all"
    }
  }
}
```

### Expected Behavior
OpsGenie Integration should have a filter looking like this
![image](https://user-images.githubusercontent.com/85218982/183631199-5ed1cb48-b08c-4ab4-b413-d0c714de9fe8.png)

### Actual Behavior
Opsgenie Integration has a filter looking like this: 
![image](https://user-images.githubusercontent.com/85218982/183631336-86a7644e-4d50-4f0c-9637-943c8284da42.png)

### Steps to Reproduce
See code above

### Important Factoids
To put it bluntly, the whole provider is a complete mess. The documentation lacks proper real-world examples, and is full of bugs and inconsitencies. I dare you to write some TF code, run apply, then run plan / apply again - you WILL see several changes pending despite no code has been changed. Very disappointing from a paying customer's perspective.

**Comment by Kerwood** [comment]
> To put it bluntly, the whole provider is a complete mess. The documentation lacks proper real-world examples, and is full of bugs and inconsitencies.

Agree..

> Very disappointing from a paying customer's perspective.

Absolutely agree. We are also a paying customer and deploy our infrastructure as code. This has been a real struggle with Opsgenie, and still is. Current issues are that integration actions and alert policies change every time you do a plan, which is a mess when you have jobs that run your IaaC.
Concidering giving PagerDuty a go.

If you use IaaC Opsgenie is not the way to go.

**Comment by upstream-dmahlberg** [comment]
We ended up deleting our Terraform code and configure OpsGenie by hand now since that caused way less trouble than our IaaC approach. This is quite frustrating as the fact that OpsGenie offers a terraform provider for configuration was one of the main reasons causing us to choose OpsGenie in the first place. Lesson learned...

**Comment by Kerwood** [comment]
Haha, yes.. Remember to check issues and PRs :D

**Comment by nvanheuverzwijn** [comment]
Alright, for everyone coming here and saying this is bugged... you are right. It's completely bugged. However, here is a fix or a workaround I should say.

I debugged their code to the bone. I went through all 7 gates of hell to retrieve this information.

The first thing you want to do, is to get rid of the `key` value. That's right. It's useless. Don't even bother adding this value, it does not serve any purpose but to annoy you with validation that when `key` is there, field needs to be `extra-properties`.

The second thing you want to do, is to change your field type from `extra-properties` to `extra_properties_key_prefix-KEYNAME`. Yes, that's right. That's all you have to do and surprise, it will work. But why ? This field type is not documented, what the hell is this ? That's right, it's not documented, it's not even in the code but that's what the server returns when you set extra properties via the GUI and you ask what the value is.

Let's say your condition is this :
```
conditions {
                  expected_value = "infra"
                  field          = "extra-properties"
                  key            = "owner"
                  not            = false
                  operation      = "equals"
                }
```
You want to have this :

```
conditions {
                  expected_value = "infra"
                  field          = "extra_properties_key_prefix-owner"
                  not            = false
                  operation      = "equals"
                }
```

And it will work.

**Comment by nvanheuverzwijn** [comment]
@Kerwood @upstream-dmahlberg I found the workaround if you guys are interested.

**Comment by nvanheuverzwijn** [comment]
This issue : https://github.com/sensu-plugins/sensu-plugins-opsgenie/issues/51 is also relevant and the fact that the `key` value is not documented in the integration api. The problem is that the `conditions` block is a copy paste of the team routing rules `conditions` block. It's not the same type in the api but considered the same type in the provider.

**Comment by upstream-dmahlberg** [comment]
Holy sh..... I don't even want to imagine what kind of hoops you had to jump through to get to the bottom of this. I salute you, kind stranger.

**Comment by nvanheuverzwijn** [comment]
@upstream-dmahlberg I did walk on the surface of the sun. It wasn't that bad. They do have good integration test so it was easy to test things out.

**Comment by koushik-swaminathan** [comment]
Hi @nvanheuverzwijn @upstream-dmahlberg, sorry about the experience you've had with the terraform provider. We're trying to fix all the issues actively, thank you for your contributions :)

**Comment by upstream-dmahlberg** [comment]
Hi @koushik-swaminathan , with all due respect - this post was created about 1,5 yrs ago. Altough I appreciate that someone is taking care of this, we seized using the terraform provider and have moved on a long time ago.

**Comment by nvanheuverzwijn** [comment]
@koushik-swaminathan can you merge the MR ?
