### ISSUE TITLE
No darwin_arm64 package for v0.6.11?

### ISSUE THREAD

**Issue by ryan-codaio** [opsgenie/terraform-provider-opsgenie#323]
Hi,

I'm running Terraform v1.2.3 on darwin_arm64 (M1 Mac). I was running opsgenie v0.6.10 and it was working fine, but then we tried upgrading to v0.6.11, but `terraform init` fails:

```
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/opsgenie/opsgenie v0.6.11 does not have a package available for your current platform,
│ darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
│ Other versions of this provider may have different platforms supported.
```

It looks like there was no package built for darwin_arm64.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set opsgenie provider version to 0.6.11
2. Run `terraform init -upgrade`

**Comment by debayande** [comment]
Believe this has been fixed in https://github.com/opsgenie/terraform-provider-opsgenie/issues/317; what's needed now is a release of `v0.6.13` of the provider.

@fnuva: Apologies for chasing up on this one, but could you please cut a release of `v0.6.13` of the provider? Thanks.
