### ISSUE TITLE
Updating default team routing rule results in forbidden message

### ISSUE THREAD

**Issue by catalinmares** [opsgenie/terraform-provider-opsgenie#344]
Hi everyone,

I noticed an issue with the opsgenie_team_routing_rule Terraform resource. Looks like whenever I try updating the default team routing rule I get a 403 Forbidden message.

### Terraform Version
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_team_routin_rule

### Terraform Configuration Files
```hcl
data "opsgenie_team" "BNS-AQUILA" {
	name = "BNS-AQUILA"
}

resource "opsgenie_team_routing_rule" "default" {
    name                    = "Default Routing Rule"
    team_id                 = data.opsgenie_team.BNS-AQUILA.id
    order                   = 2
    timezone                = "CET"
    is_default              = true

    criteria {
        type                = "match-all"
    }

    notify {
        type                = "none"
    }
}
```

### Debug Output
https://gist.github.com/catalinmares/c8800bbb593615ae87ee19a9fe9c9655#file-debug-txt

### Expected Behavior
For the default team routing rule just the resource update itself should happen.

### Actual Behavior
Instead, after updating the routing rule, another call is made to also update its order and it fails with 403 Forbidden.

### Steps to Reproduce
1. Import the default routing rule from Opsgenie
`terraform import opsgenie_team_routing_rule.default <teamId>/<ruleId>
2. Update the resource configuration according to the one from the state:
`terraform show`
3. Modify the resource as needed
`terraform apply`

### References
Looks like the issue is coming from here: 

https://github.com/opsgenie/terraform-provider-opsgenie/blob/93fbf594ffcb9b18fa20dcefefe3f4b46f1d69f4/opsgenie/resource_opsgenie_team_routing_rule.go#L309

From what I noticed, the change order call is made no matter the routing rule is default or not, so for the default routing rules this call will fail in Opsgenie, since it is not allowed to change the order of the default routing rule.

**Comment by frknyldz** [comment]
Hi @catalinmares , thanks for the contribution and that detailed explanation.
We released a new [version](https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.19) and verified that the issue seems to be resolved. I'm closing this issue and I'm kindly asking you to test it with the latest version. If you encounter a problem again feel free to reopen this issue.
Gday

**Comment by catalinmares** [comment]
It works like a charm, thank you!
