### ISSUE TITLE
Crash when updating from 0.6.14 to 0.6.18

### ISSUE THREAD

**Issue by jakeyheath** [opsgenie/terraform-provider-opsgenie#351]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.2.6

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_opsgenie_escalation

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "opsgenie_schedule" "core-infra-eng" {
  name = "Central - Infra Eng_schedule"
}

data "opsgenie_schedule" "data-infra-eng" {
  name = "Central - Data Infra_schedule"
}

data "opsgenie_team" "core-infra-eng" {
  name = "Central - Infra Eng"
}

data "opsgenie_team" "data-infra-eng" {
  name = "Central - Data Infra"
}

resource "opsgenie_service" "service" {
  name    = var.service_name
  team_id = lower(var.owner_team) == "core infra eng" ? data.opsgenie_team.core-infra-eng.id : data.opsgenie_team.data-infra-eng.id
}

data "opsgenie_escalation" "escalation-data-infra-eng" {
  name = "Central - Data Infra_escalation"
}

data "opsgenie_escalation" "escalation-infra-eng" {
  name = "Central - Infra Eng_escalation"
}
```

### Debug Output
https://gist.github.com/jakeyheath/696639964051f11b63118bd1643b5cf3

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. run the configuration using 6.14
1. `terraform apply`
2. see everything working okay
3. upgrade to 6.18
4. `terraform apply`
5. crash

### Important Factoids

I am running the same code but updated the versions

**Comment by koushik-swaminathan** [comment]
Hi @jakeyheath, closing this issue for now. Please let me know if you're facing the same issue in the latest versions as well.
