### ISSUE TITLE
Provider doesn't allow to define routing rules

### ISSUE THREAD

**Issue by echoAlexey** [opsgenie/terraform-provider-opsgenie#37]
Hi,

Provider doesn't support routing rule definition for teams. 

After setting up team, escalation and schedule with terraform, it is impossible to manage routing rule to route alerts to new escalation policy, default is used.

**Comment by echoAlexey** [comment]
This also pops another problem: if terraform managed escalation policy is used by some routing rule - terraform will not be able to manage it properly (e.g. delete).

**Comment by MRinalducci** [comment]
We'd like to get this supported too by the Terraform provider 👍

**Comment by ffahri** [comment]
This will be implemented asap and will be released on v0.2.6

**Comment by ffahri** [comment]
Hey https://github.com/terraform-providers/terraform-provider-opsgenie/pull/52 pr merged.
version 0.2.6 will be released today
