### ISSUE TITLE
Allow terraform to manage default schedule/escalation for newly created team

### ISSUE THREAD

**Issue by echoAlexey** [opsgenie/terraform-provider-opsgenie#38]
Hi,

When new team is created with terraform - schedule and escalation is also created.

These entities are not managed by terraform. From API I see we cannot prevent opsgenie from creating them. 

Please add mechanism to support managing these entities and update them if schedule/escalation with default name is created. Should support running this in single "apply".

**Comment by ffahri** [comment]
I agree will think of implementation and add this to provider. Thank you for filling up this issue @echoAlexey

**Comment by jaceq** [comment]
@ffahri I think easiest approach would be similar to: https://www.terraform.io/docs/providers/google/r/container_cluster.html
There is the same case, resource creates a 'default' sub-resource so guys introduced a parameter: ```remove_default_node_pool = true```
Basically after creation, they make another call to actually remove created resource. This could get the job done here by calling 'Delete schedule' [https://docs.opsgenie.com/docs/schedule-api#section-delete-schedule](https://docs.opsgenie.com/docs/schedule-api#section-delete-schedule)

**Comment by miroag** [comment]
Agree the easiest way will be to call delete of the default schedule, escalation and routing rules after creation.
Update: I did not manage to find a way to delete the default routing rule, instead I had to set it to None

**Comment by jaceq** [comment]
@miroag did you do that with TF?
I had a quick look into adding remove_default_node_pool = true attribute into team, but there was some problem with finding out the ID of default rule. Then I re-focused to adding Notification Policy support.

@ffahri Do you have enough power to request API / SDK change? If so could you request for Team Create call to return ID of default routing rule? (or ideally also schedule and rotation)

**Comment by miroag** [comment]
@jaceq 
No, I did with Python as external data_source:

in tf code
```
data "external" "delete_defaults" {
  program    = ["python3", "${path.module}/delete_defaults.py"]
  depends_on = [opsgenie_team.team]

  query = {
    # arbitrary map from strings to strings, passed
    # to the external program as the data query.
    team_id       = opsgenie_team.team.id
    team_name     = opsgenie_team.team.name
    ops_genie_key = var.opsgenie_api_key
  }
}
```

python code:

```
# This script will remove defaults created by OpsGenie when creating a new team:
# <team name>_escalation and <team name>_schedule. It's not possible to delete default routing rule, so silence it
# python module used is https://pypi.org/project/terraform-external-data/

import os
import sys
import requests
import json

from terraform_external_data import terraform_external_data

url = 'https://api.opsgenie.com/v2'


@terraform_external_data
def delete_defaults(query):
    """
    Handler to delete default resources
    """
    # just to ease eventual debugging
    # with open('params-dump', 'w') as f:
    #     f.write(json.dumps(query))

    results = {}
    api_key = query["ops_genie_key"]
    if not len(api_key):
        api_key = os.environ.get('OPSGENIE_API_KEY')
    if not api_key:
        raise AttributeError('OPSGENIE_API_KEY is not set in the environment or passed as argument')
    headers = {'Authorization': f'GenieKey {api_key}',}
    params = (('identifierType', 'name'),)

    # we cannot delete default routing rule, which is created automatically with new team being created.
    # It's not possible to delete thedefault routing rule, so I merely silence it
    response = requests.get(f'{url}/teams/{query["team_id"]}/routing-rules', headers=headers)
    data = json.loads(response.content.decode(encoding='ascii', errors='ignore'))['data']
    for r in data:
        # default routing rule uses <teamname>_escalation and can have identical name
        if r['isDefault']:
            response = requests.patch(f'{url}/teams/{query["team_id"]}/routing-rules/{r["id"]}', headers=headers,
                                      json={"notify": {"type": "none"}})
            response.raise_for_status()

    # remove default escalation
    response = requests.get(f'{url}/escalations/{query["team_name"]}_escalation', headers=headers, params=params)
    if response.status_code < 300:
        response = requests.delete(f'{url}/escalations/{query["team_name"]}_escalation', headers=headers, params=params)
        response.raise_for_status()

    # remove default schedule
    response = requests.get(f'{url}/schedules/{query["team_name"]}_schedule', headers=headers, params=params)
    if response.status_code < 300:
        response = requests.delete(f'{url}/schedules/{query["team_name"]}_schedule', headers=headers, params=params)
        response.raise_for_status()

    # Terraform requires the values you return be strings,
    # so terraform_external_data will error if they aren't.
    return results


if __name__ == '__main__':
    # Always protect Python scripts from import side effects with
    # a condition to check the __name__. Not specifically necessary
    # for terraform_external_data, but it's a best practice in general.
    delete_defaults()

```

**Comment by ffahri** [comment]
I have created internal ticket for returning default resource id's with create response.

**Comment by brandonrising** [comment]
Any updates on that ticket @ffahri ?

**Comment by akshayatplivo** [comment]
Facing the same issue.

**Comment by mrajeshh** [comment]
Stuck with the same issue while decoupling or managing the default schedule, escalation policy for newly created team with  terraform.
Could someone please provide latest update!

**Comment by ffahri** [comment]
Until waiting the internal ticket, belive we can add an option to delete newly created schedule and escalation similiar to this comment
https://github.com/terraform-providers/terraform-provider-opsgenie/issues/38#issuecomment-575144266

**Comment by RTodorov** [comment]
Hi @ffahri , sorry to keep asking but this bug is a bit annoying and the issue is quite old for a commercial product such as OG, any chance it's being looked at?

**Comment by ffahri** [comment]
https://github.com/opsgenie/terraform-provider-opsgenie/pull/174/files

I prepared the PR and i'll make tests and if its all green we can introduce it. 

```
remove_default_resources = true
```

this will remove escalation and schedule also changes team routing rule to None.
