### ISSUE TITLE
Resource opsgenie_email_integration don't have owner_team_id variable

### ISSUE THREAD

**Issue by MRinalducci** [opsgenie/terraform-provider-opsgenie#40]
Hi,

I noticed that resource opsgenie_email_integration don't have owner_team_id variable as described in the official Terraform documentation: 

https://www.terraform.io/docs/providers/opsgenie/r/email_integration.html#owner_team_id
or
https://github.com/terraform-providers/terraform-provider-opsgenie/blob/master/website/docs/r/email_integration.html.markdown

opsgenie_email_integration schema:
https://github.com/terraform-providers/terraform-provider-opsgenie/blob/a54d92d1605cc534eed1c3a477f368dbe1f65184/opsgenie/resource_opsgenie_email_integration.go#L20-L60

Compared to opsgenie_api_integration schema:
https://github.com/terraform-providers/terraform-provider-opsgenie/blob/a54d92d1605cc534eed1c3a477f368dbe1f65184/opsgenie/resource_opsgenie_api_integration.go#L49-L51

**Comment by ffahri** [comment]
Thank you for the filling up this issue this is going to be added to schema asap

**Comment by ffahri** [comment]
It seems our go-sdk-v2 doesnt have this in create struct. I will make the necessary changes first in sdk-v2 then updated provider.

**Comment by MRinalducci** [comment]
Hi @ffahri thank you for your quick feedback.
Excellent, I'll wait the fix.

**Comment by ffahri** [comment]
Updated repository and documents waiting release for today: v0.2.5
