### ISSUE TITLE
Cannot create user with 'Owner' role

### ISSUE THREAD

**Issue by MRinalducci** [opsgenie/terraform-provider-opsgenie#41]
Hi,

I tried to create a user with an 'Owner' role using opsgenie_user resource, but when I specify `role      = "Owner"` it creates a user with an 'User' role.
And there is no error returned by `terraform apply`.
When I specify 'Admin' as role it is working and creates a user with an 'Admin' role.

By the way, I created an api key with all rights.

**Comment by ffahri** [comment]
Hey @MRinalducci thank you for filling up this issue. Opsgenie API selects User role as a default if requested role does not exist or not allowed. 
Using Opsgenie API we cannot set Owner role while creating user. I will also be asking this behaviour internal thank you

**Comment by MRinalducci** [comment]
Hi @ffahri thank you for your feedback.

In the documentation the role 'Owner' is mentioned:

* `role` - (Required) The Role assigned to the User. Either a built-in such as 'Owner', 'Admin' or 'User' - or the name of a custom role.

If it is not allowed (seems logic for security reason) maybe you can mention it in the documentation or remove it ?

https://github.com/terraform-providers/terraform-provider-opsgenie/blob/master/website/docs/r/user.html.markdown

**Comment by ffahri** [comment]
Yes i will delete from there with this release https://github.com/terraform-providers/terraform-provider-opsgenie/issues/40 👍

**Comment by MRinalducci** [comment]
Ok 👍

**Comment by avishnyakov** [comment]
Just stumbled the same problem. Put "Owner",TF did not made change neither failed.
