### ISSUE TITLE
Resource opsgenie_email_integration does not have filtering options

### ISSUE THREAD

**Issue by bjaworski3** [opsgenie/terraform-provider-opsgenie#46]
The `opsgenie_email_integration` resources looks to not support adding the more advanced filtering for email alerts. These allow filtering for specific email addresses, text in the message, etc, before alerting from the email.

https://docs.opsgenie.com/docs/creating-alerts-via-email#section-create-alert-action

Could this be supported in terraform?

**Comment by ffahri** [comment]
Yes our api supports integration actions i will create issues for this and add to provider
Thank you for filling up the issue @bjaworski3

**Comment by kiwibel** [comment]
Hey @ffahri. Any ETA for this? 
We would like to manage integration actions for CloudWatch alarms with terraform. 
Should I create a similar request for `opsgenie_api_integration` resource?

Thanks!

**Comment by ffahri** [comment]
Added this to our internal sprint @kiwibel.
I created integration actions resource issue #114 lets track this in that page

**Comment by ffahri** [comment]
email filtering will be added with integration actions, it cannot added without it. issue is on #114
