### ISSUE TITLE
Opsgenie provider can' t configure Notification Rules

### ISSUE THREAD

**Issue by dalvarezquiroga** [opsgenie/terraform-provider-opsgenie#48]
Hello,

I'm afraid that Terraform Opsgenie provider cannot enable user to modify notification rules.
It looks you can only configure the user contacts and that is it.

https://www.terraform.io/docs/providers/opsgenie/r/user_contact.html

Thanks

**Comment by jaceq** [comment]
I've added this and created PR: https://github.com/terraform-providers/terraform-provider-opsgenie/pull/68 
Please note that not all attributes are included.
