### ISSUE TITLE
0.12 support

### ISSUE THREAD

**Issue by gregswift** [opsgenie/terraform-provider-opsgenie#49]
Appreciate that yall got this updated and maintained now! Just creating this ticket cause i found no answer searching the webs on where yall are with 0.12 support.  Didn't see any existing issues, PRs, or branches that seemed to indicate movement that direction. 

### Terraform Version
0.12.x

### Steps to Reproduce
1. install terraform 0.12
2. install latest opsgenie provider
3. run terraform plan
4. get errors like in the linked discussion.

### References
https://discuss.hashicorp.com/t/issue-running-opsgenie-provider-with-terraform-0-12-7/3044/4

**Comment by ffahri** [comment]
Hey @gregswift thanks ! Yes we are supporting Terraform 0.12.x as well and migrated Terraform Plugin SDK a month ago https://github.com/terraform-providers/terraform-provider-opsgenie/pull/35 (https://www.terraform.io/docs/extend/plugin-sdk.html) .
I cannot reproduce the situation talked in discussion neither in EU and USA regions. 

https://github.com/terraform-providers/terraform-provider-opsgenie/issues/32
