### ISSUE TITLE
Terraform Refresh does not remove opsgenie_api_integration resource if not found

### ISSUE THREAD

**Issue by teddylear** [opsgenie/terraform-provider-opsgenie#51]
### Terraform Version
Terrform v0.11.14

### Affected Resource(s)
- opsgenie_api_integration

### Terraform Configuration Files
```hcl
data "opsgenie_team" "opsgenie" {
  name = "test_team"
}

resource "opsgenie_api_integration" "cloudwatch" {
  name  = "test_A"
  type   = "CloudWatch"
  owner_team_id = "${data.opsgenie_team.opsgenie.id}"
}
```

### Expected Behavior
During terraform refresh, opsgenie_api_integration is removed from state file if not found in opsgenie aka getting a 404 response

### Actual Behavior
Terraform errors out and crashes. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Manually delete opsgenie_api_integration named "test_A" under team "test_team"
3. `terraform plan -refresh=true

**Comment by ffahri** [comment]
Wrong comment to this issue. 
Will try to reproduce this issue

**Comment by ffahri** [comment]
Hey, thats the expected behaviour. It will be deleted and Terraform tries to get this integration/any resource via its state file. 
Therefore it gets 404. 
We can delete this from state using terraform state rm command
``` 
 terraform state rm 'opsgenie_api_integration.cloudwatch'
```

**Comment by teddylear** [comment]
@ffahri That isn't the expected behavior with other resources from other providers. For example during refresh if something is not found in AWS provider, it is just removed from that statefile in most cases. Yes the state rm will resolve the issue, but that is not a good developer experience. Can we update so that refresh just removes from statefile instead of crashing the refresh?

**Comment by ffahri** [comment]
I looked at other providers as well and yes that makes sense. I will create an issue for this to update all of our resources. 
I just need to figure out notify people about this state removal.
@teddylear thanks for pointing this

**Comment by ffahri** [comment]
I think this will be added before the next release
