### ISSUE TITLE
Can't import opsgenie_schedule_rotation resource

### ISSUE THREAD

**Issue by cthulhu** [opsgenie/terraform-provider-opsgenie#55]
Can't import opsgenie_schedule_rotation resource.

### Terraform Version
```
>terraform version
Terraform v0.12.18
+ provider.opsgenie v0.2.6
```

### Terraform Configuration Files
```hcl
resource "opsgenie_schedule_rotation" "ops_rotation" { 
  schedule_id = opsgenie_schedule.ops.id
  name        = "Ops team rotation"
  start_date  = "2019-01-01T00:00:00Z"
  type        ="weekly"

  participant {
    type = "user"
    id   = opsgenie_user.John_Dou.id
  }
}
```

### Expected Behavior
Resource imported successfully 

### Actual Behavior
Error message:

```
Error: Schedule identifier cannot be empty.
```

### Steps to Reproduce
Import resource with ID from UI:

```
terraform import opsgenie_schedule_rotation.ops_rotation ID-FROM-UI-XXXX-XXXXXXXXX
```

**Comment by ffahri** [comment]
Hey @cthulhu is opsgenie_schedule.ops.id parameter are correct and contains schedule id ?

**Comment by cthulhu** [comment]
Hi @ffahri! 
Yes, I even tried to replace that with string ID since I though it doesn't evaluate it from the resource. Same behaviour.

**Comment by ffahri** [comment]
@cthulhu thanks for the raising up this issue. Will fix this error asap. It seems this error will happen all of the dependent resources while importing

**Comment by nervous-inhuman** [comment]
Hello @ffahri! 

Any progress with this issue? We want to track OpsGenie schedules w/ Terraform + Git, however, this issue is blocking us.

Thanks.

**Comment by ffahri** [comment]
Hey @oneohtrix and @cthulhu thank you for this issue. 
https://github.com/terraform-providers/terraform-provider-opsgenie/pull/60
this pr will fix this issue. 
this resources with parents need to be imported using parentId/resourceId syntax.
I added these to documentation as well. 
These will be in v0.2.7 release and we expect this release will be available in max 24h
