### ISSUE TITLE
OpsGenie provider isn't working anymore

### ISSUE THREAD

**Issue by tcarrondo** [opsgenie/terraform-provider-opsgenie#6]
### Expected Behavior
Terraform should have created 2 users and a team, following official docs. 

### Actual Behavior
Didn't work:
Client error occurred; Response Code: 410, Response Body: {"code":32,"error":"DeprecatedApiException[API v1 is deprecated. Please refer https://docs.opsgenie.com/docs/dashboard/rest-api for details of the new version]"}

### Important Factoids
OpsGenie API was updated and provider stopped working

### References
https://docs.opsgenie.com/docs/api-overview

**Comment by ffahri** [comment]
Opsgenie Terraform Provider is updated and will be released soon
