### ISSUE TITLE
[Feature Request] Notification Policies

### ISSUE THREAD

**Issue by miroag** [opsgenie/terraform-provider-opsgenie#63]
Hi there,

It will be nice to have notification (team/global) policies implemented

**Comment by jaceq** [comment]
Hi,

It seems that notification policies are only team specific.
I have added this resource and opened this PR for it: https://github.com/terraform-providers/terraform-provider-opsgenie/pull/67

**Comment by miroag** [comment]
Super ! Thanks

**Comment by ffahri** [comment]
Merged ! Thanks @jaceq
