### ISSUE TITLE
This provider is scheduled to be archived on September 27th, 2018.

### ISSUE THREAD

**Issue by randomcamel** [opsgenie/terraform-provider-opsgenie#7]
This Terraform provider is scheduled to be [archived](https://help.github.com/articles/archiving-repositories/) on September 27th, 2018. HashiCorp may archive providers when they have insufficient activity to maintain them at a level consistent with our open source guidelines and community expectations.

What does archiving mean?

1. The code repository and all commit, issue, and PR history will still be available.
1. Existing released binaries will remain available on the releases site and available to `terraform init`.
1. Documentation for the provider will remain on the Terraform website.
1. Issues and pull requests are not being monitored, merged, or added.
1. No new releases will be published.
1. Nightly acceptance tests may not be run.

If anyone from the community is willing to maintain this provider, please reach out to the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) at **terraform-provider-dev@hashicorp.com**.

**Comment by ffahri** [comment]
Provider updated and no longer archived
