### ISSUE TITLE
opsgenie_team_routing_rule Timezone required issue

### ISSUE THREAD

**Issue by dtomasi** [opsgenie/terraform-provider-opsgenie#71]
### Terraform Version
Terraform v0.12.21

### Affected Resource(s)
- opsgenie_team_routing_rule

### Expected Behavior
```
# opsgenie_team_routing_rule.default will be updated in-place
     resource "opsgenie_team_routing_rule" "default" {
        id       = "d1bc3347-8b64-sz4v-9cfd-1c025ba63882"
        name     = "Default Routing Rule"
        order    = 0
        team_id  = "53912ba9-72a7-3hsd-982a-cf50e0797222"
        timezone = "Europe/Berlin"

        criteria {
            type = "match-all"
        }

       notify {
          id   = (known after apply)
          type = "escalation"
        }
    }
```
### Actual Behavior

Without timezone property:
```
Error: Missing required argument

  on team.tf line 15, in resource "opsgenie_team_routing_rule" "default":
  15: resource "opsgenie_team_routing_rule" "default" {

The argument "timezone" is required, but no definition was found.
```

With timezone property

```
Error: Error occurred with Status code: 422, Message: Default routing rule can not have timezone., Took: 0.005000, RequestId: xxxxxxxxxxx

  on team.tf line 15, in resource "opsgenie_team_routing_rule" "default":
  15: resource "opsgenie_team_routing_rule" "default" {
```

**Comment by ffahri** [comment]
We need to change required to optional for timezone field. Thank you for raising this issue

**Comment by dtomasi** [comment]
Hey, sorry for the late response. 
I´m not sure if it´s enough to remove the required option. As you might have seen the error says that it cannot contain the timezone. Probably the API Documentation of Opsgenie is outdated. The only way I got around was to remove the timezone entirely and recompile the provider.

**Comment by ffahri** [comment]
this was already implemented -> optional

**Comment by ffahri** [comment]
@wyardley can you explain a bit more of your situation

**Comment by wyardley** [comment]
@ffahri absolutely! and happy to make a new issue if I've misunderstood the one here!

Basically, we have a team, and schedules. The schedules already have a timezone defined. We imported our teams, routing rules, and escalation policies. Just seemed odd to me that we had to explicitly define the timezone in the routing rule.

```hcl
resource "opsgenie_team" "foo" {
  name        = "foo"
  description = "foo team"

  ignore_members = true
}

resource "opsgenie_schedule" "foo_schedule" {
  name          = "foo_schedule"
  enabled       = true
  owner_team_id = opsgenie_team.foo.id
  timezone      = var.timezone
}

resource "opsgenie_team_routing_rule" "foo_low_priority" {
  name     = "foo - Working hours,  low priority (< P3)"
  team_id  = opsgenie_team.foo.id
  timezone = var.timezone

  criteria {
    type = "match-all-conditions"

    conditions {
      expected_value = "P3"
      field          = "priority"
      not            = false
      operation      = "less-than"
    }
  }

  notify {
    name = opsgenie_escalation.foo_low_priority.name
    type = "escalation"
  }
}
```

Looking in the web UI, I am required to set timezone here, so maybe this is intentional? I thought the fact that it was becoming optional meant there was somewhere (team level?) that it could inherit a default from.
