### ISSUE TITLE
Cannot create user with 'Owner' role: TF should fail but does not

### ISSUE THREAD

**Issue by avishnyakov** [opsgenie/terraform-provider-opsgenie#73]
Same-same as the following issue:
* Cannot create user with 'Owner' role #41

Terraform should fail early during plan/deploy instead of giving false impression of a successful operation. It took some time to figure our why Owner would not work.

**Comment by jaceq** [comment]
@avishnyakov Problem here is that API itself accepts that and returns no error (and at the same time it creates a 'user').
I have also asked about that and was told (which btw. makes sense) that given that API keys can be created by Admins, it would be a security issue  to be able to create Owners.
On the other hand it could be checked on TF side to workaround that.

**Comment by ffahri** [comment]
We can add pre-check for terraform when creating new user.

**Comment by avishnyakov** [comment]
That would be great.

**Comment by ffahri** [comment]
I will create an issue internally for api does not return 200 when Owner type user creation. 
Adding this check to terraform will not be true because it may be allowed in future to add Owner user etc.
