### ISSUE TITLE
Implement all fields for notification rule

### ISSUE THREAD

**Issue by ffahri** [opsgenie/terraform-provider-opsgenie#76]

**Comment by jaceq** [comment]
What happened to this resource?
Why was it reverted?

**Comment by ffahri** [comment]
Hey @jaceq 
https://github.com/terraform-providers/terraform-provider-opsgenie/pull/68#issuecomment-595749446

At that time it  was returned 422 i dont want to block other bugfixes. We can introduce if its ok again

**Comment by jaceq** [comment]
Ah I totally missed that, my bad.
I will try to check what is breaking there when I have a bit of time.
