### ISSUE TITLE
Add "ownerTeam.name" to opsgenie_api_integration

### ISSUE THREAD

**Issue by igaskin** [opsgenie/terraform-provider-opsgenie#77]
### Terraform Version
```
$ terraform --version
Terraform v0.12.21
+ provider.opsgenie v0.2.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_api_integration

### Terraform Configuration Files
```hcl
resource "opsgenie_api_integration" "prometheus" {
  count = length(local.prometheus_integration_names)
  name = "${lower(data.opsgenie_team.default.name)}-prometheus-${local.prometheus_integration_names[count.index]}"
  type = "Prometheus"

  enabled                        = true
  allow_write_access             = true
  ignore_responders_from_payload = false
  suppress_notifications         = false
  owner_team_id                  = data.opsgenie_team.default.id
}
```

### Expected Behavior
When creating or importing the resource `opsgenie_api_integration` it should include the optional field `owner_team_name`.

### Actual Behavior
Currently only `owner_team_id` is allowed to be set as an option.

This problem is also present when importing existing opsgenie_api_integration's, since the ownerTeam field can be set as such:

Owner team of the integration, consisting id and/or name of the owner team.
https://docs.opsgenie.com/docs/integration-api#section-create-api-based-integration

Since the opsgenie_api_integration resource only accepts owner_team_id there is no way to import an existing opsgenie_api_integration that has the form:
```
{
    "ownerTeam": {
        "name":"operations_team"
    }
}
```
or

```
{
    "ownerTeam": {
        "id":"8418d193-2alp-4490-b331-8c02cdd196b7",
        "name":"operations_team"
    }
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import opsgenie_api_integration.prometheus <integration id>`
2. `terraform apply`
```
Error: Error occurred with Status code: 403, Message: You can not assign integration to another team, Took: 0.005000, RequestId: a4023235-18c3-4d98-b6c1-16243ced80eb```
```
### References

- GH-64

**Comment by milonjames** [comment]
@igaskin have you managed to find any workaround for this issue. I am also facing the same problem while trying to import an existing integration and then apply the changes.

**Comment by igaskin** [comment]
> integration

No I haven't.  There is no workaround currently for this issue, besides not importing the existing api integrations.  My plan was to submit a PR to the this provider to fix this issue.

**Comment by milonjames** [comment]
@igaskin Check my comment on the issue https://github.com/terraform-providers/terraform-provider-opsgenie/issues/50
I think same issue there also.

**Comment by ffahri** [comment]
Hey i added owner_team_id with v0.3.0 version. 
However changing owner team bug still waits upstream I will track this issue with another issue in github about ownerTeam change. But this import should be fixed @igaskin.
Im closing this issue if this still persist please reopen.
