### ISSUE TITLE
[BUG] Cannot update an expired maintenance

### ISSUE THREAD

**Issue by KevinLoganBS** [opsgenie/terraform-provider-opsgenie#90]
You can only edit the end_date of an open maintenance, and it's not possible to delete a completed maintenance.

It looks like if a maintenance changes, then it needs to create a new one. The workaround we're using now, is to always taint this resource in our automations.

### Terraform Version
```
Terraform v0.12.24
+ provider.opsgenie v0.2.9
```

### Affected Resource(s)
- opsgenie_maintenance

### Terraform Configuration Files
```hcl
resource "opsgenie_maintenance" "maintenance" {
  description = "maintenance"

  time {
    type       = "schedule"
    start_date = timestamp()
    end_date   = timeadd(timestamp(), "10m")
  }

  rules {
    state = "enabled"

    entity {
      type = "policy"
      id   = "<id>"
    }
  }
}
```

### Expected Behavior
Create a new maintenance.

### Actual Behavior
`Error: Error occurred with Status code: 422, Message: Cannot update an expired maintenance`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Let maintenance expire
3. `terraform apply`

**Comment by ffahri** [comment]
Hey @KevinLoganBS 
Thanks for filling up this issue. It seems terraform update cannot change maintenance end date. 
I will creating an issue for this.

I tried to delete a completed maintenance and its works.

**Comment by ffahri** [comment]
And go-sdk-v2 currrently not support edit maintenance end date function. I will create an issue for  sdk after this finished i will implement this to Provider

**Comment by ffahri** [comment]
Our api does not support edit expired maintenances. I edited provider to change end date for active maintenances and this will be in next release
