### ISSUE TITLE
Terraform crash when creating schedule rotation with no time restrictions

### ISSUE THREAD

**Issue by munkyjunky** [opsgenie/terraform-provider-opsgenie#94]
When creating an `opsgenie_schedule_rotation`, if `time_restriction` is not specified Terraform crashes. The resource I'm trying to create should not have any time restrictions, so the key has been omitted (the docs don't say it's required from what I can see). Adding in some time restrictions seems to fix the issue, but doesn't give me the resource I'm wanting to create. 

When applying this configuration in Terraform, the correct resource is created in OpsGenie, but I don't think it gets stored in TF state (the plugin crashes before that point). 

### Terraform Version
Terraform v0.12.24
+ provider.opsgenie v0.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_schedule_rotation

### Terraform Configuration Files
```hcl
resource "opsgenie_schedule_rotation" "rotation" {
  name = "Rotation"
  schedule_id = opsgenie_schedule.out_of_hours.id
  start_date = "2020-04-13T08:30:00Z"
  type = "weekly"
  length = 1

  participant {
    type = "user"
    id = data.opsgenie_user.sw.id
  }

}
```

### Debug Output
https://gist.github.com/munkyjunky/3ad9640dfecbcbca9bd409ece338c407

**Comment by ffahri** [comment]
Thank you for reporting this bug i will fix this asap

**Comment by ffahri** [comment]
Sorry for disruption @munkyjunky . The reason is we recently add read restrictions field and write to state commit. Since its non mandatory field it can be empty and we did not check this. One of our e2e test should create rotation without time restriction. 

I added necessary changes and tests to master and v0.3.1 will be released today

**Comment by ffahri** [comment]
Version 0.3.1 is released

**Comment by munkyjunky** [comment]
Thank you for the quick turnaround on this! I've upgraded to 0.3.1 and everything now works as expected.
